CREATE TABLE IF NOT EXISTS cash_receipts (
  id bigint unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id bigint unsigned NOT NULL,
  tenant_id bigint unsigned NOT NULL,
  rent_obligation_id bigint unsigned NOT NULL,
  receipt_number varchar(64) NOT NULL,
  amount_cents bigint NOT NULL,
  currency char(3) NOT NULL DEFAULT 'EUR',
  received_at date NOT NULL,
  note varchar(512) NULL,
  status varchar(32) NOT NULL DEFAULT 'confirmed',
  operation_id varchar(64) NOT NULL,
  idempotency_key varchar(191) NOT NULL,
  recorded_by_user_id bigint unsigned NOT NULL,
  recorded_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  voided_at timestamp NULL,
  voided_by_user_id bigint unsigned NULL,
  void_reason varchar(512) NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY idx_cash_receipts_user_receipt_number (user_id, receipt_number),
  UNIQUE KEY idx_cash_receipts_user_idempotency (user_id, idempotency_key),
  KEY idx_cash_receipts_user_obligation_status (user_id, rent_obligation_id, status),
  KEY idx_cash_receipts_user_tenant_received (user_id, tenant_id, received_at),
  CONSTRAINT fk_cash_receipts_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_cash_receipts_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  CONSTRAINT fk_cash_receipts_obligation FOREIGN KEY (rent_obligation_id) REFERENCES rent_obligations(id) ON DELETE CASCADE,
  CONSTRAINT fk_cash_receipts_recorded_by FOREIGN KEY (recorded_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_cash_receipts_voided_by FOREIGN KEY (voided_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
