CREATE TABLE IF NOT EXISTS dunning_sender_configs (
  id bigint unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id bigint unsigned NOT NULL,
  display_name varchar(191) NOT NULL,
  reply_to_email varchar(191) NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY idx_dunning_sender_configs_user (user_id),
  CONSTRAINT fk_dunning_sender_configs_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS dunning_send_attempts (
  id bigint unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id bigint unsigned NOT NULL,
  tenant_id bigint unsigned NOT NULL,
  rent_obligation_id bigint unsigned NOT NULL,
  period_month date NOT NULL,
  recipient_email varchar(191) NOT NULL,
  template_kind varchar(32) NOT NULL,
  subject varchar(512) NOT NULL,
  body text NOT NULL,
  expected_amount_cents bigint NOT NULL,
  paid_amount_cents bigint NOT NULL,
  balance_amount_cents bigint NOT NULL,
  currency char(3) NOT NULL DEFAULT 'EUR',
  sender_display_name varchar(191) NOT NULL,
  reply_to_email varchar(191) NOT NULL,
  service_from_email varchar(191) NOT NULL,
  delivery_status varchar(32) NOT NULL,
  provider_message_id varchar(191) NULL,
  error_message varchar(512) NULL,
  operation_id varchar(64) NOT NULL,
  request_key varchar(191) NOT NULL,
  retry_of_attempt_id bigint unsigned NULL,
  requested_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  sent_at timestamp NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY idx_dunning_attempts_user_request_obligation (user_id, request_key, rent_obligation_id),
  KEY idx_dunning_attempts_user_period (user_id, period_month, tenant_id),
  KEY idx_dunning_attempts_user_obligation_status (user_id, rent_obligation_id, delivery_status, sent_at),
  CONSTRAINT fk_dunning_attempts_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_dunning_attempts_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  CONSTRAINT fk_dunning_attempts_obligation FOREIGN KEY (rent_obligation_id) REFERENCES rent_obligations(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
