-- Generated by test-data/rosewood/extract.py -- do not edit by hand.
-- Stage match: create the lazy rent obligations the app would create on
-- first page load, confirm the pre-matched bank transactions, then
-- backfill rent_obligations.paid_amount_cents/status from the confirmed
-- allocations. The backfill is the whole point of this stage: the
-- dashboard sums the stored column, so without it 已收 reads 0
-- (design.md §6.1, migrations/013_dedupe_rent_obligations.sql:106-136).
--
-- Requires @uid; scoped to the four Rosewood addresses:
--   '116 Kimmage Rd W Dublin 12', '78 Old County Road Dublin 12', '72 Walkinstown Rd Dublin 12', '169 Windmill Park Dublin 12'

START TRANSACTION;

-- 1) one obligation per tenant-month, exactly like
--    ensureMonthlyObligations (obligations.go:172-200): on the 1st, for the
--    tenant's own share, lazily generated.
--    Idempotency has two guards on purpose. INSERT IGNORE leans on the
--    unique key idx_rent_obligations_lazy_tenant_period that migration 013
--    adds (that migration is the task dependency, and the app applies it on
--    startup); NOT EXISTS makes a re-run a no-op even on a database where
--    013 has not been applied yet, where there is nothing to conflict with.
INSERT IGNORE INTO rent_obligations
  (user_id, tenant_id, tenant_name_snapshot, period_month, due_date, expected_amount_cents,
   paid_amount_cents, currency, status, record_status, generated_by)
SELECT @uid, t.id, t.name, m.period_month, m.period_month, t.monthly_rent_cents,
       0, t.currency, 'open', 'active', 'lazy'
  FROM tenants t
  JOIN (
    SELECT '2026-05-01' AS period_month UNION ALL
    SELECT '2026-06-01' AS period_month UNION ALL
    SELECT '2026-07-01' AS period_month UNION ALL
    SELECT '2026-08-01' AS period_month UNION ALL
    SELECT '2026-09-01' AS period_month UNION ALL
    SELECT '2026-10-01' AS period_month UNION ALL
    SELECT '2026-11-01' AS period_month UNION ALL
    SELECT '2026-12-01' AS period_month
  ) m
 WHERE t.user_id = @uid
   AND t.room_address IN ('116 Kimmage Rd W Dublin 12', '78 Old County Road Dublin 12', '72 Walkinstown Rd Dublin 12', '169 Windmill Park Dublin 12')
   AND t.monthly_rent_cents > 0
   AND m.period_month >= t.rent_start_date
   AND m.period_month <= t.rent_end_date
   AND NOT EXISTS (SELECT 1 FROM rent_obligations o
                    WHERE o.user_id = t.user_id
                      AND o.tenant_id = t.id
                      AND o.rent_charge_id IS NULL
                      AND o.period_month = m.period_month);

-- 2) confirm the bank transactions that the ledger already ties to a
--    tenancy. The rule (mirrored in extract.py, which reports the same
--    split in review.json): a transaction the ledger recorded as a short
--    payment, or one whose stable key hashes into the deterministic
--    quarter, becomes a confirmed rent allocation to that month.
INSERT IGNORE INTO payment_allocations
  (user_id, payment_transaction_id, rent_obligation_id, tenant_id, amount_cents, allocation_kind,
   idempotency_key, status, confirmed_by_user_id, confirmed_at, confirmation_source, note)
SELECT @uid, pt.id, o.id, t.id,
       LEAST(pt.amount_cents, o.expected_amount_cents - o.paid_amount_cents),
       'rent', CONCAT('rosewood-alloc:', pt.stable_transaction_key), 'confirmed',
       @uid, COALESCE(pt.transaction_time, CURRENT_TIMESTAMP), 'auto_match', 'Rosewood 收租明细导入自动匹配'
  FROM payment_transactions pt
  JOIN tenants t ON t.user_id = @uid AND t.name = pt.payer_name
  JOIN rent_obligations o ON o.user_id = @uid AND o.tenant_id = t.id
                         AND o.rent_charge_id IS NULL
                         AND o.period_month = pt.parsed_period_month
 WHERE pt.user_id = @uid
   AND pt.direction = 'income'
   AND pt.amount_cents > 0
   AND pt.stable_transaction_key LIKE 'rosewood:%'
   AND (pt.amount_cents < o.expected_amount_cents
        OR CRC32(pt.stable_transaction_key) % 4 = 0);

-- 3) reflect the allocations on the transaction itself, the way
--    allocateTransactionInTx does (transaction_allocation.go:144-230).
UPDATE payment_transactions pt
  JOIN payment_allocations pa ON pa.payment_transaction_id = pt.id
                             AND pa.user_id = pt.user_id AND pa.status = 'confirmed'
  JOIN rent_obligations o ON o.id = pa.rent_obligation_id
   SET pt.match_status = CASE WHEN pa.amount_cents >= o.expected_amount_cents THEN 'matched' ELSE 'partial' END,
       pt.matched_tenant_id = pa.tenant_id,
       pt.match_reason = CONCAT('收租明细导入自动匹配 · 租金月 ', DATE_FORMAT(o.period_month, '%Y-%m'))
 WHERE pt.user_id = @uid AND pt.stable_transaction_key LIKE 'rosewood:%';

-- 4) THE BACKFILL. Copied from the final UPDATE of
--    migrations/013_dedupe_rent_obligations.sql so the stored projection
--    matches what projectRentObligation/obligationStatus recompute
--    (obligations.go:165-170, ledger.go:119-139):
--      paid = confirmed rent allocations + confirmed EUR cash receipts
--      status priority needs_review > voided > paid > partial
--                        > overdue > open, overdue on the Dublin day.
SET @rosewood_year = YEAR(UTC_TIMESTAMP());
SET @rosewood_dst_start = DATE_ADD(DATE_SUB(STR_TO_DATE(CONCAT(@rosewood_year, '-03-31'), '%Y-%m-%d'), INTERVAL (DAYOFWEEK(STR_TO_DATE(CONCAT(@rosewood_year, '-03-31'), '%Y-%m-%d')) - 1) DAY), INTERVAL 1 HOUR);
SET @rosewood_dst_end = DATE_ADD(DATE_SUB(STR_TO_DATE(CONCAT(@rosewood_year, '-10-31'), '%Y-%m-%d'), INTERVAL (DAYOFWEEK(STR_TO_DATE(CONCAT(@rosewood_year, '-10-31'), '%Y-%m-%d')) - 1) DAY), INTERVAL 1 HOUR);
SET @rosewood_today = CASE WHEN UTC_TIMESTAMP() >= @rosewood_dst_start AND UTC_TIMESTAMP() < @rosewood_dst_end THEN DATE(DATE_ADD(UTC_TIMESTAMP(), INTERVAL 1 HOUR)) ELSE DATE(UTC_TIMESTAMP()) END;

UPDATE rent_obligations o
  JOIN (
    SELECT o2.id AS obligation_id, o2.user_id AS user_id,
           (SELECT COALESCE(SUM(pa.amount_cents), 0)
              FROM payment_allocations pa
             WHERE pa.rent_obligation_id = o2.id
               AND pa.user_id = o2.user_id
               AND pa.status = 'confirmed'
               AND (pa.allocation_kind = 'rent' OR pa.allocation_kind = ''))
         + (SELECT COALESCE(SUM(cr.amount_cents), 0)
              FROM cash_receipts cr
             WHERE cr.rent_obligation_id = o2.id
               AND cr.user_id = o2.user_id
               AND cr.tenant_id = o2.tenant_id
               AND cr.status = 'confirmed'
               AND cr.amount_cents > 0
               AND UPPER(TRIM(cr.currency)) = 'EUR'
               AND UPPER(TRIM(cr.currency)) = UPPER(TRIM(o2.currency))) AS paid_cents
      FROM rent_obligations o2
     WHERE o2.rent_charge_id IS NULL
       AND o2.user_id = @uid
       AND o2.tenant_id IN (SELECT t.id FROM tenants t
                             WHERE t.user_id = @uid AND t.room_address IN ('116 Kimmage Rd W Dublin 12', '78 Old County Road Dublin 12', '72 Walkinstown Rd Dublin 12', '169 Windmill Park Dublin 12'))
  ) p ON p.obligation_id = o.id AND p.user_id = o.user_id
   SET o.paid_amount_cents = p.paid_cents,
       o.status = CASE
         WHEN o.status = 'needs_review' THEN 'needs_review'
         WHEN o.record_status = 'voided' THEN 'voided'
         WHEN p.paid_cents >= o.expected_amount_cents THEN 'paid'
         WHEN p.paid_cents > 0 THEN 'partial'
         WHEN o.due_date < @rosewood_today THEN 'overdue'
         ELSE 'open'
       END;

COMMIT;

