-- Generated by test-data/rosewood/extract.py -- do not edit by hand.
-- Stage data: the ledger's lease structure and bank feed. Idempotent.
-- Requires @uid (the acting user id); scripts/seed-rosewood.sh sets it.
--
-- Every row this file creates or deletes is scoped to these four
-- addresses and the fixture keys below: '116 Kimmage Rd W Dublin 12', '78 Old County Road Dublin 12', '72 Walkinstown Rd Dublin 12', '169 Windmill Park Dublin 12'

-- 1) fixture keys, used by both the DELETE and the INSERT below
DROP TEMPORARY TABLE IF EXISTS _rs_property;
CREATE TEMPORARY TABLE _rs_property (
  k varchar(64) NOT NULL PRIMARY KEY,
  name varchar(191) NOT NULL,
  city_region varchar(191) NULL,
  address text NULL,
  timezone varchar(64) NOT NULL,
  status varchar(32) NOT NULL
) ENGINE=InnoDB;
INSERT INTO _rs_property (k, name, city_region, address, timezone, status) VALUES
  ('kimmage', '116 Kimmage Rd W Dublin 12', 'Dublin', '116 Kimmage Rd W Dublin 12', 'Europe/Dublin', 'active')      ,
  ('oldcounty', '78 Old County Road Dublin 12', 'Dublin', '78 Old County Road Dublin 12', 'Europe/Dublin', 'active'),
  ('walkinstown', '72 Walkinstown Rd Dublin 12', 'Dublin', '72 Walkinstown Rd Dublin 12', 'Europe/Dublin', 'active'),
  ('windmill', '169 Windmill Park Dublin 12', 'Dublin', '169 Windmill Park Dublin 12', 'Europe/Dublin', 'active')   ;
DROP TEMPORARY TABLE IF EXISTS _rs_room;
CREATE TEMPORARY TABLE _rs_room (
  k varchar(64) NOT NULL PRIMARY KEY,
  property_key varchar(64) NOT NULL,
  room_label varchar(191) NOT NULL,
  capacity int NOT NULL,
  monthly_rent_cents bigint NOT NULL,
  due_day int NOT NULL,
  active_from date NOT NULL,
  status varchar(32) NOT NULL
) ENGINE=InnoDB;
INSERT INTO _rs_room (k, property_key, room_label, capacity, monthly_rent_cents, due_day, active_from, status) VALUES
  ('kimmage-01', 'kimmage', '01', 1, 75000, 1, '2026-05-01', 'active')       ,
  ('kimmage-02', 'kimmage', '02', 2, 132000, 1, '2026-05-01', 'active')      ,
  ('kimmage-03', 'kimmage', '03', 2, 129000, 1, '2026-05-01', 'active')      ,
  ('kimmage-04', 'kimmage', '04', 1, 88000, 1, '2026-05-01', 'active')       ,
  ('kimmage-05', 'kimmage', '05', 3, 150000, 1, '2026-05-01', 'active')      ,
  ('kimmage-06', 'kimmage', '06', 2, 136000, 1, '2026-05-01', 'active')      ,
  ('oldcounty-1', 'oldcounty', '1', 1, 68000, 1, '2026-05-01', 'active')     ,
  ('oldcounty-2', 'oldcounty', '2', 2, 120000, 1, '2026-05-01', 'active')    ,
  ('oldcounty-3', 'oldcounty', '3', 2, 62500, 1, '2026-05-01', 'active')     ,
  ('oldcounty-4', 'oldcounty', '4', 2, 120000, 1, '2026-05-01', 'active')    ,
  ('oldcounty-5', 'oldcounty', '5', 2, 120000, 1, '2026-05-01', 'active')    ,
  ('walkinstown-1', 'walkinstown', '1', 1, 70000, 1, '2026-05-01', 'active') ,
  ('walkinstown-2', 'walkinstown', '2', 2, 116000, 1, '2026-05-01', 'active'),
  ('walkinstown-3', 'walkinstown', '3', 2, 60000, 1, '2026-05-01', 'active') ,
  ('walkinstown-4', 'walkinstown', '4', 2, 122000, 1, '2026-05-01', 'active'),
  ('walkinstown-5', 'walkinstown', '5', 2, 99000, 1, '2026-05-01', 'active') ,
  ('walkinstown-6', 'walkinstown', '6', 1, 73000, 1, '2026-05-01', 'active') ,
  ('walkinstown-7', 'walkinstown', '7', 1, 73000, 1, '2026-05-01', 'active') ,
  ('walkinstown-8', 'walkinstown', '8', 1, 80000, 1, '2026-05-01', 'active') ,
  ('windmill-01', 'windmill', '01', 1, 60000, 1, '2026-05-01', 'active')     ,
  ('windmill-02', 'windmill', '02', 1, 90000, 1, '2026-05-01', 'active')     ,
  ('windmill-03', 'windmill', '03', 2, 125000, 1, '2026-05-01', 'active')    ,
  ('windmill-04', 'windmill', '04', 1, 80000, 1, '2026-05-01', 'active')     ,
  ('windmill-05', 'windmill', '05', 2, 130000, 1, '2026-05-01', 'active')    ,
  ('windmill-06', 'windmill', '06', 1, 120000, 1, '2026-05-01', 'active')    ;
DROP TEMPORARY TABLE IF EXISTS _rs_tenant;
CREATE TEMPORARY TABLE _rs_tenant (
  k varchar(64) NOT NULL PRIMARY KEY,
  name varchar(191) NOT NULL,
  display_alias varchar(191) NULL,
  monthly_rent_cents bigint NOT NULL,
  currency char(3) NOT NULL,
  billing_start_date date NOT NULL,
  due_day int NOT NULL,
  rent_start_date date NOT NULL,
  rent_end_date date NULL,
  status varchar(32) NOT NULL,
  room_label varchar(191) NOT NULL,
  room_address text NOT NULL,
  property_hint varchar(191) NULL
) ENGINE=InnoDB;
INSERT INTO _rs_tenant (k, name, display_alias, monthly_rent_cents, currency, billing_start_date, due_day, rent_start_date, rent_end_date, status, room_label, room_address, property_hint) VALUES
  ('kimmage-01-anselmo-2026-05', 'Anselmo Augusto dos Santos Rodrigues', NULL, 75000, 'EUR', '2026-05-01', 1, '2026-05-01', '2026-12-31', 'active', '01', '116 Kimmage Rd W Dublin 12', '116 Kimmage Rd W Dublin 12')                   ,
  ('kimmage-02-chidera-2026-05', 'Chidera Nnaeto', NULL, 66000, 'EUR', '2026-05-01', 1, '2026-05-01', '2026-12-31', 'active', '02', '116 Kimmage Rd W Dublin 12', '116 Kimmage Rd W Dublin 12')                                         ,
  ('kimmage-02-siddarth-2026-05', 'Siddarth Janagouda', NULL, 66000, 'EUR', '2026-05-01', 1, '2026-05-01', '2026-12-31', 'active', '02', '116 Kimmage Rd W Dublin 12', '116 Kimmage Rd W Dublin 12')                                    ,
  ('kimmage-03-abdellatif-2026-09', 'Abdellatif', 'ABDELLATIF 原5405）', 66000, 'EUR', '2026-09-01', 1, '2026-09-01', '2026-12-31', 'active', '03', '116 Kimmage Rd W Dublin 12', '116 Kimmage Rd W Dublin 12')                           ,
  ('kimmage-03-neil-2026-05', 'Neil Jose', 'Neil', 63000, 'EUR', '2026-05-01', 1, '2026-05-01', '2026-12-31', 'active', '03', '116 Kimmage Rd W Dublin 12', '116 Kimmage Rd W Dublin 12')                                               ,
  ('kimmage-03-sravan-2026-05', 'Sravan', NULL, 66000, 'EUR', '2026-05-01', 1, '2026-05-01', '2026-08-31', 'active', '03', '116 Kimmage Rd W Dublin 12', '116 Kimmage Rd W Dublin 12')                                                  ,
  ('kimmage-04-chenxi-2026-06', 'Chenxi Liu', NULL, 88000, 'EUR', '2026-06-01', 1, '2026-06-01', '2026-12-31', 'active', '04', '116 Kimmage Rd W Dublin 12', '116 Kimmage Rd W Dublin 12')                                              ,
  ('kimmage-04-lilian-2026-05', 'Lilian', NULL, 88000, 'EUR', '2026-05-01', 1, '2026-05-01', '2026-05-31', 'active', '04', '116 Kimmage Rd W Dublin 12', '116 Kimmage Rd W Dublin 12')                                                  ,
  ('kimmage-05-anush-2026-05', 'Bala Anush Choudhary', 'Anush', 50000, 'EUR', '2026-05-01', 1, '2026-05-01', '2026-12-31', 'active', '05', '116 Kimmage Rd W Dublin 12', '116 Kimmage Rd W Dublin 12')                                  ,
  ('kimmage-05-hardik-2026-05', 'Hardik Gattu', NULL, 50000, 'EUR', '2026-05-01', 1, '2026-05-01', '2026-12-31', 'active', '05', '116 Kimmage Rd W Dublin 12', '116 Kimmage Rd W Dublin 12')                                            ,
  ('kimmage-05-priteesh-2026-05', 'Priteesh Nandan', NULL, 50000, 'EUR', '2026-05-01', 1, '2026-05-01', '2026-12-31', 'active', '05', '116 Kimmage Rd W Dublin 12', '116 Kimmage Rd W Dublin 12')                                       ,
  ('kimmage-06-devansh-2026-07', 'Devansh Chauhan', NULL, 68000, 'EUR', '2026-07-01', 1, '2026-07-01', '2026-12-31', 'active', '06', '116 Kimmage Rd W Dublin 12', '116 Kimmage Rd W Dublin 12')                                        ,
  ('kimmage-06-noel-2026-05', 'Noel Jose', 'Noel', 68000, 'EUR', '2026-05-01', 1, '2026-05-01', '2026-12-31', 'active', '06', '116 Kimmage Rd W Dublin 12', '116 Kimmage Rd W Dublin 12')                                               ,
  ('kimmage-06-pavel-2026-05', 'Pavel Ionut Alexandru', NULL, 68000, 'EUR', '2026-05-01', 1, '2026-05-01', '2026-06-30', 'active', '06', '116 Kimmage Rd W Dublin 12', '116 Kimmage Rd W Dublin 12')                                    ,
  ('oldcounty-1-thant-2026-05', 'Thant Lynn Htet', NULL, 68000, 'EUR', '2026-05-01', 1, '2026-05-01', '2026-12-31', 'active', '1', '78 Old County Road Dublin 12', '78 Old County Road Dublin 12')                                      ,
  ('oldcounty-2-sai-2026-05', 'Sai Chitraksh Amram', NULL, 60000, 'EUR', '2026-05-01', 1, '2026-05-01', '2026-06-30', 'active', '2', '78 Old County Road Dublin 12', '78 Old County Road Dublin 12')                                    ,
  ('oldcounty-2-sriram-2026-07', 'Sriram Samala', NULL, 60000, 'EUR', '2026-07-01', 1, '2026-07-01', '2026-12-31', 'active', '2', '78 Old County Road Dublin 12', '78 Old County Road Dublin 12')                                       ,
  ('oldcounty-2-tajudin-2026-05', 'Tajudin Shaik', 'Taj', 60000, 'EUR', '2026-05-01', 1, '2026-05-01', '2026-12-31', 'active', '2', '78 Old County Road Dublin 12', '78 Old County Road Dublin 12')                                     ,
  ('oldcounty-3-nghiem-2026-05', 'Nghiem Duc Minh (Chris)', NULL, 62500, 'EUR', '2026-05-01', 1, '2026-05-01', '2026-06-30', 'active', '3', '78 Old County Road Dublin 12', '78 Old County Road Dublin 12')                             ,
  ('oldcounty-3-pham-2026-05', 'Pham Trung Hieu (Harvey)', 'PHAM TRUNG HIEU (Harvey', 62500, 'EUR', '2026-05-01', 1, '2026-05-01', '2026-06-30', 'active', '3', '78 Old County Road Dublin 12', '78 Old County Road Dublin 12')         ,
  ('oldcounty-3-wahajullah-2026-07', 'Wahajullah Khan', NULL, 62500, 'EUR', '2026-07-01', 1, '2026-07-01', '2026-12-31', 'active', '3', '78 Old County Road Dublin 12', '78 Old County Road Dublin 12')                                 ,
  ('oldcounty-4-anish-2026-09', 'Anish Kishor', NULL, 60000, 'EUR', '2026-09-01', 1, '2026-09-01', '2026-12-31', 'active', '4', '78 Old County Road Dublin 12', '78 Old County Road Dublin 12')                                         ,
  ('oldcounty-4-arslan-2026-07', 'Arslan Arshad', NULL, 60000, 'EUR', '2026-07-01', 1, '2026-07-01', '2026-08-31', 'active', '4', '78 Old County Road Dublin 12', '78 Old County Road Dublin 12')                                       ,
  ('oldcounty-4-asad-2026-07', 'Asad Raza', NULL, 60000, 'EUR', '2026-07-01', 1, '2026-07-01', '2026-08-31', 'active', '4', '78 Old County Road Dublin 12', '78 Old County Road Dublin 12')                                             ,
  ('oldcounty-4-chu-2026-05', 'Chu Sandy Kyaw', NULL, 60000, 'EUR', '2026-05-01', 1, '2026-05-01', '2026-06-30', 'active', '4', '78 Old County Road Dublin 12', '78 Old County Road Dublin 12')                                         ,
  ('oldcounty-4-henisha-2026-09', 'Henisha Anish Raut', NULL, 60000, 'EUR', '2026-09-01', 1, '2026-09-01', '2026-12-31', 'active', '4', '78 Old County Road Dublin 12', '78 Old County Road Dublin 12')                                 ,
  ('oldcounty-4-wai-2026-05', 'Wai Aung', NULL, 60000, 'EUR', '2026-05-01', 1, '2026-05-01', '2026-06-30', 'active', '4', '78 Old County Road Dublin 12', '78 Old County Road Dublin 12')                                               ,
  ('oldcounty-5-ananya-2026-07', 'Ananya M', NULL, 60000, 'EUR', '2026-07-01', 1, '2026-07-01', '2026-12-31', 'active', '5', '78 Old County Road Dublin 12', '78 Old County Road Dublin 12')                                            ,
  ('oldcounty-5-min-2026-05', 'Min Myat Moe', NULL, 60000, 'EUR', '2026-05-01', 1, '2026-05-01', '2026-06-30', 'active', '5', '78 Old County Road Dublin 12', '78 Old County Road Dublin 12')                                           ,
  ('oldcounty-5-nyan-2026-05', 'Nyan Lin Htut', NULL, 60000, 'EUR', '2026-05-01', 1, '2026-05-01', '2026-06-30', 'active', '5', '78 Old County Road Dublin 12', '78 Old County Road Dublin 12')                                         ,
  ('oldcounty-5-satvik-2026-07', 'Satvik Talawar', NULL, 60000, 'EUR', '2026-07-01', 1, '2026-07-01', '2026-12-31', 'active', '5', '78 Old County Road Dublin 12', '78 Old County Road Dublin 12')                                      ,
  ('walkinstown-1-abhishek-2026-05', 'Abhishek Bhagwat', NULL, 70000, 'EUR', '2026-05-01', 1, '2026-05-01', '2026-06-30', 'active', '1', '72 Walkinstown Rd Dublin 12', '72 Walkinstown Rd Dublin 12')                                  ,
  ('walkinstown-1-eider-2026-07', 'Eider Esneir', NULL, 70000, 'EUR', '2026-07-01', 1, '2026-07-01', '2026-12-31', 'active', '1', '72 Walkinstown Rd Dublin 12', '72 Walkinstown Rd Dublin 12')                                         ,
  ('walkinstown-2-ardra-2026-05', 'Ardra M Punathil', 'Ardra Punathil; ARDRA PUNATHIL; ARDRA M', 58000, 'EUR', '2026-05-01', 1, '2026-05-01', '2026-12-31', 'active', '2', '72 Walkinstown Rd Dublin 12', '72 Walkinstown Rd Dublin 12'),
  ('walkinstown-2-meghana-2026-05', 'Meghana Vipin Mehta', 'MEGHANA VIPIN', 58000, 'EUR', '2026-05-01', 1, '2026-05-01', '2026-12-31', 'active', '2', '72 Walkinstown Rd Dublin 12', '72 Walkinstown Rd Dublin 12')                     ,
  ('walkinstown-3-avila-2026-05', 'Avila Almeida', NULL, 60000, 'EUR', '2026-05-01', 1, '2026-05-01', '2026-07-31', 'active', '3', '72 Walkinstown Rd Dublin 12', '72 Walkinstown Rd Dublin 12')                                        ,
  ('walkinstown-3-blancy-2026-05', 'Blancy Mendes', NULL, 60000, 'EUR', '2026-05-01', 1, '2026-05-01', '2026-07-31', 'active', '3', '72 Walkinstown Rd Dublin 12', '72 Walkinstown Rd Dublin 12')                                       ,
  ('walkinstown-3-domingo-2026-09', 'Domingo Jose Cristo Sanches', NULL, 60000, 'EUR', '2026-09-01', 1, '2026-09-01', '2026-12-31', 'active', '3', '72 Walkinstown Rd Dublin 12', '72 Walkinstown Rd Dublin 12')                        ,
  ('walkinstown-4-durga-2026-07', 'Durga Nagendra', NULL, 61000, 'EUR', '2026-07-01', 1, '2026-07-01', '2026-12-31', 'active', '4', '72 Walkinstown Rd Dublin 12', '72 Walkinstown Rd Dublin 12')                                       ,
  ('walkinstown-4-lohit-2026-07', 'Lohit Dinesh', NULL, 61000, 'EUR', '2026-07-01', 1, '2026-07-01', '2026-12-31', 'active', '4', '72 Walkinstown Rd Dublin 12', '72 Walkinstown Rd Dublin 12')                                         ,
  ('walkinstown-4-nagendra-2026-05', 'Nagendra Gonugunta', NULL, 61000, 'EUR', '2026-05-01', 1, '2026-05-01', '2026-06-30', 'active', '4', '72 Walkinstown Rd Dublin 12', '72 Walkinstown Rd Dublin 12')                                ,
  ('walkinstown-4-raj-2026-05', 'Raj', NULL, 61000, 'EUR', '2026-05-01', 1, '2026-05-01', '2026-06-30', 'active', '4', '72 Walkinstown Rd Dublin 12', '72 Walkinstown Rd Dublin 12')                                                    ,
  ('walkinstown-5-amal-2026-05', 'Amal Surya', NULL, 49500, 'EUR', '2026-05-01', 1, '2026-05-01', '2026-12-31', 'active', '5', '72 Walkinstown Rd Dublin 12', '72 Walkinstown Rd Dublin 12')                                            ,
  ('walkinstown-5-rohith-2026-05', 'Rohith Murali', NULL, 49500, 'EUR', '2026-05-01', 1, '2026-05-01', '2026-06-30', 'active', '5', '72 Walkinstown Rd Dublin 12', '72 Walkinstown Rd Dublin 12')                                       ,
  ('walkinstown-5-suryakarthik-2026-07', 'Suryakarthik', NULL, 49500, 'EUR', '2026-07-01', 1, '2026-07-01', '2026-12-31', 'active', '5', '72 Walkinstown Rd Dublin 12', '72 Walkinstown Rd Dublin 12')                                  ,
  ('walkinstown-6-bhuvaneswaran-2026-05', 'Bhuvaneswaran', 'Bhuvan D', 73000, 'EUR', '2026-05-01', 1, '2026-05-01', '2026-06-30', 'active', '6', '72 Walkinstown Rd Dublin 12', '72 Walkinstown Rd Dublin 12')                          ,
  ('walkinstown-6-kaushik-2026-07', 'Kaushik Kannan', NULL, 73000, 'EUR', '2026-07-01', 1, '2026-07-01', '2026-12-31', 'active', '6', '72 Walkinstown Rd Dublin 12', '72 Walkinstown Rd Dublin 12')                                     ,
  ('walkinstown-7-bhuvaneswaran-2026-07', 'Bhuvaneswaran', 'BHUVANES WARAN', 73000, 'EUR', '2026-07-01', 1, '2026-07-01', '2026-12-31', 'active', '7', '72 Walkinstown Rd Dublin 12', '72 Walkinstown Rd Dublin 12')                    ,
  ('walkinstown-7-kaushik-2026-05', 'Kaushik Kannan', NULL, 73000, 'EUR', '2026-05-01', 1, '2026-05-01', '2026-06-30', 'active', '7', '72 Walkinstown Rd Dublin 12', '72 Walkinstown Rd Dublin 12')                                     ,
  ('walkinstown-8-ajay-2026-05', 'Ajay Pandikasala', 'Ajay', 80000, 'EUR', '2026-05-01', 1, '2026-05-01', '2026-12-31', 'active', '8', '72 Walkinstown Rd Dublin 12', '72 Walkinstown Rd Dublin 12')                                    ,
  ('windmill-01-yong-2026-05', 'Yong Liu', NULL, 60000, 'EUR', '2026-05-01', 1, '2026-05-01', '2026-12-31', 'active', '01', '169 Windmill Park Dublin 12', '169 Windmill Park Dublin 12')                                               ,
  ('windmill-02-abdulrahman-2026-05', 'Abdulrahman Elfeky', 'Abdulrhman elfeky', 90000, 'EUR', '2026-05-01', 1, '2026-05-01', '2026-12-31', 'active', '02', '169 Windmill Park Dublin 12', '169 Windmill Park Dublin 12')               ,
  ('windmill-03-gleice-2026-05', 'Gleice Cristina Rodrigues da Silva', NULL, 62500, 'EUR', '2026-05-01', 1, '2026-05-01', '2026-12-31', 'active', '03', '169 Windmill Park Dublin 12', '169 Windmill Park Dublin 12')                   ,
  ('windmill-03-vitor-2026-05', 'Vitor Hugo Silva Carvalho', NULL, 62500, 'EUR', '2026-05-01', 1, '2026-05-01', '2026-12-31', 'active', '03', '169 Windmill Park Dublin 12', '169 Windmill Park Dublin 12')                             ,
  ('windmill-04-rafael-2026-05', 'Rafael de Souza Santos Cunha', NULL, 80000, 'EUR', '2026-05-01', 1, '2026-05-01', '2026-12-31', 'active', '04', '169 Windmill Park Dublin 12', '169 Windmill Park Dublin 12')                         ,
  ('windmill-05-atif-2026-05', 'Atif Anam', NULL, 65000, 'EUR', '2026-05-01', 1, '2026-05-01', '2026-12-31', 'active', '05', '169 Windmill Park Dublin 12', '169 Windmill Park Dublin 12')                                              ,
  ('windmill-05-mohd-2026-06', 'Mohd Anamul Haq', NULL, 65000, 'EUR', '2026-06-01', 1, '2026-06-01', '2026-12-31', 'active', '05', '169 Windmill Park Dublin 12', '169 Windmill Park Dublin 12')                                        ,
  ('windmill-06-qiang-2026-05', 'Qiang Li', NULL, 120000, 'EUR', '2026-05-01', 1, '2026-05-01', '2026-12-31', 'active', '06', '169 Windmill Park Dublin 12', '169 Windmill Park Dublin 12')                                             ;
DROP TEMPORARY TABLE IF EXISTS _rs_agreement;
CREATE TEMPORARY TABLE _rs_agreement (
  k varchar(128) NOT NULL PRIMARY KEY,
  room_key varchar(64) NOT NULL,
  contract_date date NULL,
  move_in_date date NULL,
  start_date date NOT NULL,
  end_date date NULL,
  monthly_rent_cents bigint NOT NULL,
  currency char(3) NOT NULL,
  due_day int NOT NULL,
  status varchar(32) NOT NULL
) ENGINE=InnoDB;
INSERT INTO _rs_agreement (k, room_key, contract_date, move_in_date, start_date, end_date, monthly_rent_cents, currency, due_day, status) VALUES
  ('kimmage-01-agreement-2026-05', 'kimmage-01', '2026-05-01', '2026-05-01', '2026-05-01', '2026-12-31', 75000, 'EUR', 1, 'active')       ,
  ('kimmage-02-agreement-2026-05', 'kimmage-02', '2026-05-01', '2026-05-01', '2026-05-01', '2026-12-31', 132000, 'EUR', 1, 'active')      ,
  ('kimmage-03-agreement-2026-05', 'kimmage-03', '2026-05-01', '2026-05-01', '2026-05-01', '2026-08-31', 129000, 'EUR', 1, 'active')      ,
  ('kimmage-03-agreement-2026-09', 'kimmage-03', '2026-09-01', '2026-09-01', '2026-09-01', '2026-12-31', 129000, 'EUR', 1, 'active')      ,
  ('kimmage-04-agreement-2026-05', 'kimmage-04', '2026-05-01', '2026-05-01', '2026-05-01', '2026-05-31', 88000, 'EUR', 1, 'active')       ,
  ('kimmage-04-agreement-2026-06', 'kimmage-04', '2026-06-01', '2026-06-01', '2026-06-01', '2026-12-31', 88000, 'EUR', 1, 'active')       ,
  ('kimmage-05-agreement-2026-05', 'kimmage-05', '2026-05-01', '2026-05-01', '2026-05-01', '2026-12-31', 150000, 'EUR', 1, 'active')      ,
  ('kimmage-06-agreement-2026-05', 'kimmage-06', '2026-05-01', '2026-05-01', '2026-05-01', '2026-06-30', 136000, 'EUR', 1, 'active')      ,
  ('kimmage-06-agreement-2026-07', 'kimmage-06', '2026-07-01', '2026-07-01', '2026-07-01', '2026-12-31', 136000, 'EUR', 1, 'active')      ,
  ('oldcounty-1-agreement-2026-05', 'oldcounty-1', '2026-05-01', '2026-05-01', '2026-05-01', '2026-12-31', 68000, 'EUR', 1, 'active')     ,
  ('oldcounty-2-agreement-2026-05', 'oldcounty-2', '2026-05-01', '2026-05-01', '2026-05-01', '2026-06-30', 120000, 'EUR', 1, 'active')    ,
  ('oldcounty-2-agreement-2026-07', 'oldcounty-2', '2026-07-01', '2026-07-01', '2026-07-01', '2026-12-31', 120000, 'EUR', 1, 'active')    ,
  ('oldcounty-3-agreement-2026-05', 'oldcounty-3', '2026-05-01', '2026-05-01', '2026-05-01', '2026-06-30', 125000, 'EUR', 1, 'active')    ,
  ('oldcounty-3-agreement-2026-07', 'oldcounty-3', '2026-07-01', '2026-07-01', '2026-07-01', '2026-12-31', 62500, 'EUR', 1, 'active')     ,
  ('oldcounty-4-agreement-2026-05', 'oldcounty-4', '2026-05-01', '2026-05-01', '2026-05-01', '2026-06-30', 120000, 'EUR', 1, 'active')    ,
  ('oldcounty-4-agreement-2026-07', 'oldcounty-4', '2026-07-01', '2026-07-01', '2026-07-01', '2026-08-31', 120000, 'EUR', 1, 'active')    ,
  ('oldcounty-4-agreement-2026-09', 'oldcounty-4', '2026-09-01', '2026-09-01', '2026-09-01', '2026-12-31', 120000, 'EUR', 1, 'active')    ,
  ('oldcounty-5-agreement-2026-05', 'oldcounty-5', '2026-05-01', '2026-05-01', '2026-05-01', '2026-06-30', 120000, 'EUR', 1, 'active')    ,
  ('oldcounty-5-agreement-2026-07', 'oldcounty-5', '2026-07-01', '2026-07-01', '2026-07-01', '2026-12-31', 120000, 'EUR', 1, 'active')    ,
  ('walkinstown-1-agreement-2026-05', 'walkinstown-1', '2026-05-01', '2026-05-01', '2026-05-01', '2026-06-30', 70000, 'EUR', 1, 'active') ,
  ('walkinstown-1-agreement-2026-07', 'walkinstown-1', '2026-07-01', '2026-07-01', '2026-07-01', '2026-12-31', 70000, 'EUR', 1, 'active') ,
  ('walkinstown-2-agreement-2026-05', 'walkinstown-2', '2026-05-01', '2026-05-01', '2026-05-01', '2026-12-31', 116000, 'EUR', 1, 'active'),
  ('walkinstown-3-agreement-2026-05', 'walkinstown-3', '2026-05-01', '2026-05-01', '2026-05-01', '2026-07-31', 120000, 'EUR', 1, 'active'),
  ('walkinstown-3-agreement-2026-09', 'walkinstown-3', '2026-09-01', '2026-09-01', '2026-09-01', '2026-12-31', 60000, 'EUR', 1, 'active') ,
  ('walkinstown-4-agreement-2026-05', 'walkinstown-4', '2026-05-01', '2026-05-01', '2026-05-01', '2026-06-30', 122000, 'EUR', 1, 'active'),
  ('walkinstown-4-agreement-2026-07', 'walkinstown-4', '2026-07-01', '2026-07-01', '2026-07-01', '2026-12-31', 122000, 'EUR', 1, 'active'),
  ('walkinstown-5-agreement-2026-05', 'walkinstown-5', '2026-05-01', '2026-05-01', '2026-05-01', '2026-06-30', 99000, 'EUR', 1, 'active') ,
  ('walkinstown-5-agreement-2026-07', 'walkinstown-5', '2026-07-01', '2026-07-01', '2026-07-01', '2026-12-31', 99000, 'EUR', 1, 'active') ,
  ('walkinstown-6-agreement-2026-05', 'walkinstown-6', '2026-05-01', '2026-05-01', '2026-05-01', '2026-06-30', 73000, 'EUR', 1, 'active') ,
  ('walkinstown-6-agreement-2026-07', 'walkinstown-6', '2026-07-01', '2026-07-01', '2026-07-01', '2026-12-31', 73000, 'EUR', 1, 'active') ,
  ('walkinstown-7-agreement-2026-05', 'walkinstown-7', '2026-05-01', '2026-05-01', '2026-05-01', '2026-06-30', 73000, 'EUR', 1, 'active') ,
  ('walkinstown-7-agreement-2026-07', 'walkinstown-7', '2026-07-01', '2026-07-01', '2026-07-01', '2026-12-31', 73000, 'EUR', 1, 'active') ,
  ('walkinstown-8-agreement-2026-05', 'walkinstown-8', '2026-05-01', '2026-05-01', '2026-05-01', '2026-12-31', 80000, 'EUR', 1, 'active') ,
  ('windmill-01-agreement-2026-05', 'windmill-01', '2026-05-01', '2026-05-01', '2026-05-01', '2026-12-31', 60000, 'EUR', 1, 'active')     ,
  ('windmill-02-agreement-2026-05', 'windmill-02', '2026-05-01', '2026-05-01', '2026-05-01', '2026-12-31', 90000, 'EUR', 1, 'active')     ,
  ('windmill-03-agreement-2026-05', 'windmill-03', '2026-05-01', '2026-05-01', '2026-05-01', '2026-12-31', 125000, 'EUR', 1, 'active')    ,
  ('windmill-04-agreement-2026-05', 'windmill-04', '2026-05-01', '2026-05-01', '2026-05-01', '2026-12-31', 80000, 'EUR', 1, 'active')     ,
  ('windmill-05-agreement-2026-05', 'windmill-05', '2026-05-01', '2026-05-01', '2026-05-01', '2026-05-31', 65000, 'EUR', 1, 'active')     ,
  ('windmill-05-agreement-2026-06', 'windmill-05', '2026-06-01', '2026-06-01', '2026-06-01', '2026-12-31', 130000, 'EUR', 1, 'active')    ,
  ('windmill-06-agreement-2026-05', 'windmill-06', '2026-05-01', '2026-05-01', '2026-05-01', '2026-12-31', 120000, 'EUR', 1, 'active')    ;
DROP TEMPORARY TABLE IF EXISTS _rs_party;
CREATE TEMPORARY TABLE _rs_party (
  agreement_key varchar(128) NOT NULL,
  tenant_key varchar(64) NOT NULL,
  responsibility_cents bigint NOT NULL,
  joined_at date NULL,
  left_at date NULL,
  status varchar(32) NOT NULL,
  PRIMARY KEY (agreement_key, tenant_key)
) ENGINE=InnoDB;
INSERT INTO _rs_party (agreement_key, tenant_key, responsibility_cents, joined_at, left_at, status) VALUES
  ('kimmage-01-agreement-2026-05', 'kimmage-01-anselmo-2026-05', 75000, '2026-05-01', '2026-12-31', 'active')            ,
  ('kimmage-02-agreement-2026-05', 'kimmage-02-siddarth-2026-05', 66000, '2026-05-01', '2026-12-31', 'active')           ,
  ('kimmage-02-agreement-2026-05', 'kimmage-02-chidera-2026-05', 66000, '2026-05-01', '2026-12-31', 'active')            ,
  ('kimmage-03-agreement-2026-05', 'kimmage-03-sravan-2026-05', 66000, '2026-05-01', '2026-08-31', 'active')             ,
  ('kimmage-03-agreement-2026-05', 'kimmage-03-neil-2026-05', 63000, '2026-05-01', '2026-12-31', 'active')               ,
  ('kimmage-03-agreement-2026-09', 'kimmage-03-abdellatif-2026-09', 66000, '2026-09-01', '2026-12-31', 'active')         ,
  ('kimmage-03-agreement-2026-09', 'kimmage-03-neil-2026-05', 63000, '2026-05-01', '2026-12-31', 'active')               ,
  ('kimmage-04-agreement-2026-05', 'kimmage-04-lilian-2026-05', 88000, '2026-05-01', '2026-05-31', 'active')             ,
  ('kimmage-04-agreement-2026-06', 'kimmage-04-chenxi-2026-06', 88000, '2026-06-01', '2026-12-31', 'active')             ,
  ('kimmage-05-agreement-2026-05', 'kimmage-05-anush-2026-05', 50000, '2026-05-01', '2026-12-31', 'active')              ,
  ('kimmage-05-agreement-2026-05', 'kimmage-05-priteesh-2026-05', 50000, '2026-05-01', '2026-12-31', 'active')           ,
  ('kimmage-05-agreement-2026-05', 'kimmage-05-hardik-2026-05', 50000, '2026-05-01', '2026-12-31', 'active')             ,
  ('kimmage-06-agreement-2026-05', 'kimmage-06-noel-2026-05', 68000, '2026-05-01', '2026-12-31', 'active')               ,
  ('kimmage-06-agreement-2026-05', 'kimmage-06-pavel-2026-05', 68000, '2026-05-01', '2026-06-30', 'active')              ,
  ('kimmage-06-agreement-2026-07', 'kimmage-06-noel-2026-05', 68000, '2026-05-01', '2026-12-31', 'active')               ,
  ('kimmage-06-agreement-2026-07', 'kimmage-06-devansh-2026-07', 68000, '2026-07-01', '2026-12-31', 'active')            ,
  ('oldcounty-1-agreement-2026-05', 'oldcounty-1-thant-2026-05', 68000, '2026-05-01', '2026-12-31', 'active')            ,
  ('oldcounty-2-agreement-2026-05', 'oldcounty-2-sai-2026-05', 60000, '2026-05-01', '2026-06-30', 'active')              ,
  ('oldcounty-2-agreement-2026-05', 'oldcounty-2-tajudin-2026-05', 60000, '2026-05-01', '2026-12-31', 'active')          ,
  ('oldcounty-2-agreement-2026-07', 'oldcounty-2-sriram-2026-07', 60000, '2026-07-01', '2026-12-31', 'active')           ,
  ('oldcounty-2-agreement-2026-07', 'oldcounty-2-tajudin-2026-05', 60000, '2026-05-01', '2026-12-31', 'active')          ,
  ('oldcounty-3-agreement-2026-05', 'oldcounty-3-nghiem-2026-05', 62500, '2026-05-01', '2026-06-30', 'active')           ,
  ('oldcounty-3-agreement-2026-05', 'oldcounty-3-pham-2026-05', 62500, '2026-05-01', '2026-06-30', 'active')             ,
  ('oldcounty-3-agreement-2026-07', 'oldcounty-3-wahajullah-2026-07', 62500, '2026-07-01', '2026-12-31', 'active')       ,
  ('oldcounty-4-agreement-2026-05', 'oldcounty-4-wai-2026-05', 60000, '2026-05-01', '2026-06-30', 'active')              ,
  ('oldcounty-4-agreement-2026-05', 'oldcounty-4-chu-2026-05', 60000, '2026-05-01', '2026-06-30', 'active')              ,
  ('oldcounty-4-agreement-2026-07', 'oldcounty-4-asad-2026-07', 60000, '2026-07-01', '2026-08-31', 'active')             ,
  ('oldcounty-4-agreement-2026-07', 'oldcounty-4-arslan-2026-07', 60000, '2026-07-01', '2026-08-31', 'active')           ,
  ('oldcounty-4-agreement-2026-09', 'oldcounty-4-henisha-2026-09', 60000, '2026-09-01', '2026-12-31', 'active')          ,
  ('oldcounty-4-agreement-2026-09', 'oldcounty-4-anish-2026-09', 60000, '2026-09-01', '2026-12-31', 'active')            ,
  ('oldcounty-5-agreement-2026-05', 'oldcounty-5-nyan-2026-05', 60000, '2026-05-01', '2026-06-30', 'active')             ,
  ('oldcounty-5-agreement-2026-05', 'oldcounty-5-min-2026-05', 60000, '2026-05-01', '2026-06-30', 'active')              ,
  ('oldcounty-5-agreement-2026-07', 'oldcounty-5-satvik-2026-07', 60000, '2026-07-01', '2026-12-31', 'active')           ,
  ('oldcounty-5-agreement-2026-07', 'oldcounty-5-ananya-2026-07', 60000, '2026-07-01', '2026-12-31', 'active')           ,
  ('walkinstown-1-agreement-2026-05', 'walkinstown-1-abhishek-2026-05', 70000, '2026-05-01', '2026-06-30', 'active')     ,
  ('walkinstown-1-agreement-2026-07', 'walkinstown-1-eider-2026-07', 70000, '2026-07-01', '2026-12-31', 'active')        ,
  ('walkinstown-2-agreement-2026-05', 'walkinstown-2-ardra-2026-05', 58000, '2026-05-01', '2026-12-31', 'active')        ,
  ('walkinstown-2-agreement-2026-05', 'walkinstown-2-meghana-2026-05', 58000, '2026-05-01', '2026-12-31', 'active')      ,
  ('walkinstown-3-agreement-2026-05', 'walkinstown-3-blancy-2026-05', 60000, '2026-05-01', '2026-07-31', 'active')       ,
  ('walkinstown-3-agreement-2026-05', 'walkinstown-3-avila-2026-05', 60000, '2026-05-01', '2026-07-31', 'active')        ,
  ('walkinstown-3-agreement-2026-09', 'walkinstown-3-domingo-2026-09', 60000, '2026-09-01', '2026-12-31', 'active')      ,
  ('walkinstown-4-agreement-2026-05', 'walkinstown-4-raj-2026-05', 61000, '2026-05-01', '2026-06-30', 'active')          ,
  ('walkinstown-4-agreement-2026-05', 'walkinstown-4-nagendra-2026-05', 61000, '2026-05-01', '2026-06-30', 'active')     ,
  ('walkinstown-4-agreement-2026-07', 'walkinstown-4-lohit-2026-07', 61000, '2026-07-01', '2026-12-31', 'active')        ,
  ('walkinstown-4-agreement-2026-07', 'walkinstown-4-durga-2026-07', 61000, '2026-07-01', '2026-12-31', 'active')        ,
  ('walkinstown-5-agreement-2026-05', 'walkinstown-5-rohith-2026-05', 49500, '2026-05-01', '2026-06-30', 'active')       ,
  ('walkinstown-5-agreement-2026-05', 'walkinstown-5-amal-2026-05', 49500, '2026-05-01', '2026-12-31', 'active')         ,
  ('walkinstown-5-agreement-2026-07', 'walkinstown-5-suryakarthik-2026-07', 49500, '2026-07-01', '2026-12-31', 'active') ,
  ('walkinstown-5-agreement-2026-07', 'walkinstown-5-amal-2026-05', 49500, '2026-05-01', '2026-12-31', 'active')         ,
  ('walkinstown-6-agreement-2026-05', 'walkinstown-6-bhuvaneswaran-2026-05', 73000, '2026-05-01', '2026-06-30', 'active'),
  ('walkinstown-6-agreement-2026-07', 'walkinstown-6-kaushik-2026-07', 73000, '2026-07-01', '2026-12-31', 'active')      ,
  ('walkinstown-7-agreement-2026-05', 'walkinstown-7-kaushik-2026-05', 73000, '2026-05-01', '2026-06-30', 'active')      ,
  ('walkinstown-7-agreement-2026-07', 'walkinstown-7-bhuvaneswaran-2026-07', 73000, '2026-07-01', '2026-12-31', 'active'),
  ('walkinstown-8-agreement-2026-05', 'walkinstown-8-ajay-2026-05', 80000, '2026-05-01', '2026-12-31', 'active')         ,
  ('windmill-01-agreement-2026-05', 'windmill-01-yong-2026-05', 60000, '2026-05-01', '2026-12-31', 'active')             ,
  ('windmill-02-agreement-2026-05', 'windmill-02-abdulrahman-2026-05', 90000, '2026-05-01', '2026-12-31', 'active')      ,
  ('windmill-03-agreement-2026-05', 'windmill-03-vitor-2026-05', 62500, '2026-05-01', '2026-12-31', 'active')            ,
  ('windmill-03-agreement-2026-05', 'windmill-03-gleice-2026-05', 62500, '2026-05-01', '2026-12-31', 'active')           ,
  ('windmill-04-agreement-2026-05', 'windmill-04-rafael-2026-05', 80000, '2026-05-01', '2026-12-31', 'active')           ,
  ('windmill-05-agreement-2026-05', 'windmill-05-atif-2026-05', 65000, '2026-05-01', '2026-12-31', 'active')             ,
  ('windmill-05-agreement-2026-06', 'windmill-05-atif-2026-05', 65000, '2026-05-01', '2026-12-31', 'active')             ,
  ('windmill-05-agreement-2026-06', 'windmill-05-mohd-2026-06', 65000, '2026-06-01', '2026-12-31', 'active')             ,
  ('windmill-06-agreement-2026-05', 'windmill-06-qiang-2026-05', 120000, '2026-05-01', '2026-12-31', 'active')           ;
DROP TEMPORARY TABLE IF EXISTS _rs_tx;
CREATE TEMPORARY TABLE _rs_tx (
  stable_transaction_key varchar(255) NOT NULL PRIMARY KEY,
  amount_cents bigint NOT NULL,
  transaction_time timestamp NULL,
  description text NULL,
  reference text NULL,
  payer_name varchar(191) NULL,
  period_month date NOT NULL
) ENGINE=InnoDB;
INSERT INTO _rs_tx (stable_transaction_key, amount_cents, transaction_time, description, reference, payer_name, period_month) VALUES
  ('rosewood:ROSEWOOD-2026-05-0001', 75000, '2026-05-09 12:00:00', 'Rosewood seed 2026-05 · Anselmo Augusto dos Santos Rodrigues', 'ROSEWOOD-2026-05-0001', 'Anselmo Augusto dos Santos Rodrigues', '2026-05-01'),
  ('rosewood:ROSEWOOD-2026-06-0002', 75000, '2026-06-10 12:00:00', 'Rosewood seed 2026-06 · Anselmo Augusto dos Santos Rodrigues', 'ROSEWOOD-2026-06-0002', 'Anselmo Augusto dos Santos Rodrigues', '2026-06-01'),
  ('rosewood:ROSEWOOD-2026-07-0003', 75000, '2026-07-11 12:00:00', 'Rosewood seed 2026-07 · Anselmo Augusto dos Santos Rodrigues', 'ROSEWOOD-2026-07-0003', 'Anselmo Augusto dos Santos Rodrigues', '2026-07-01'),
  ('rosewood:ROSEWOOD-2026-08-0004', 75000, '2026-08-12 12:00:00', 'Rosewood seed 2026-08 · Anselmo Augusto dos Santos Rodrigues', 'ROSEWOOD-2026-08-0004', 'Anselmo Augusto dos Santos Rodrigues', '2026-08-01'),
  ('rosewood:ROSEWOOD-2026-09-0005', 75000, '2026-09-13 12:00:00', 'Rosewood seed 2026-09 · Anselmo Augusto dos Santos Rodrigues', 'ROSEWOOD-2026-09-0005', 'Anselmo Augusto dos Santos Rodrigues', '2026-09-01'),
  ('rosewood:ROSEWOOD-2026-05-0006', 66000, '2026-05-06 12:00:00', 'Rosewood seed 2026-05 · Chidera Nnaeto', 'ROSEWOOD-2026-05-0006', 'Chidera Nnaeto', '2026-05-01')                                            ,
  ('rosewood:ROSEWOOD-2026-06-0007', 66000, '2026-06-07 12:00:00', 'Rosewood seed 2026-06 · Chidera Nnaeto', 'ROSEWOOD-2026-06-0007', 'Chidera Nnaeto', '2026-06-01')                                            ,
  ('rosewood:ROSEWOOD-2026-07-0008', 66000, '2026-07-08 12:00:00', 'Rosewood seed 2026-07 · Chidera Nnaeto', 'ROSEWOOD-2026-07-0008', 'Chidera Nnaeto', '2026-07-01')                                            ,
  ('rosewood:ROSEWOOD-2026-08-0009', 66000, '2026-08-09 12:00:00', 'Rosewood seed 2026-08 · Chidera Nnaeto', 'ROSEWOOD-2026-08-0009', 'Chidera Nnaeto', '2026-08-01')                                            ,
  ('rosewood:ROSEWOOD-2026-09-0010', 66000, '2026-09-10 12:00:00', 'Rosewood seed 2026-09 · Chidera Nnaeto', 'ROSEWOOD-2026-09-0010', 'Chidera Nnaeto', '2026-09-01')                                            ,
  ('rosewood:ROSEWOOD-2026-05-0011', 44000, '2026-05-17 12:00:00', 'Rosewood seed 2026-05 · Siddarth Janagouda', 'ROSEWOOD-2026-05-0011', 'Siddarth Janagouda', '2026-05-01')                                    ,
  ('rosewood:ROSEWOOD-2026-06-0012', 66000, '2026-06-18 12:00:00', 'Rosewood seed 2026-06 · Siddarth Janagouda', 'ROSEWOOD-2026-06-0012', 'Siddarth Janagouda', '2026-06-01')                                    ,
  ('rosewood:ROSEWOOD-2026-07-0013', 66000, '2026-07-19 12:00:00', 'Rosewood seed 2026-07 · Siddarth Janagouda', 'ROSEWOOD-2026-07-0013', 'Siddarth Janagouda', '2026-07-01')                                    ,
  ('rosewood:ROSEWOOD-2026-08-0014', 66000, '2026-08-20 12:00:00', 'Rosewood seed 2026-08 · Siddarth Janagouda', 'ROSEWOOD-2026-08-0014', 'Siddarth Janagouda', '2026-08-01')                                    ,
  ('rosewood:ROSEWOOD-2026-09-0015', 66000, '2026-09-21 12:00:00', 'Rosewood seed 2026-09 · Siddarth Janagouda', 'ROSEWOOD-2026-09-0015', 'Siddarth Janagouda', '2026-09-01')                                    ,
  ('rosewood:ROSEWOOD-2026-09-0016', 65000, '2026-09-22 12:00:00', 'Rosewood seed 2026-09 · Abdellatif', 'ROSEWOOD-2026-09-0016', 'Abdellatif', '2026-09-01')                                                    ,
  ('rosewood:ROSEWOOD-2026-05-0017', 63000, '2026-05-18 12:00:00', 'Rosewood seed 2026-05 · Neil Jose', 'ROSEWOOD-2026-05-0017', 'Neil Jose', '2026-05-01')                                                      ,
  ('rosewood:ROSEWOOD-2026-06-0018', 63000, '2026-06-19 12:00:00', 'Rosewood seed 2026-06 · Neil Jose', 'ROSEWOOD-2026-06-0018', 'Neil Jose', '2026-06-01')                                                      ,
  ('rosewood:ROSEWOOD-2026-07-0019', 63000, '2026-07-20 12:00:00', 'Rosewood seed 2026-07 · Neil Jose', 'ROSEWOOD-2026-07-0019', 'Neil Jose', '2026-07-01')                                                      ,
  ('rosewood:ROSEWOOD-2026-08-0020', 63000, '2026-08-21 12:00:00', 'Rosewood seed 2026-08 · Neil Jose', 'ROSEWOOD-2026-08-0020', 'Neil Jose', '2026-08-01')                                                      ,
  ('rosewood:ROSEWOOD-2026-09-0021', 63000, '2026-09-22 12:00:00', 'Rosewood seed 2026-09 · Neil Jose', 'ROSEWOOD-2026-09-0021', 'Neil Jose', '2026-09-01')                                                      ,
  ('rosewood:ROSEWOOD-2026-05-0022', 63000, '2026-05-16 12:00:00', 'Rosewood seed 2026-05 · Sravan', 'ROSEWOOD-2026-05-0022', 'Sravan', '2026-05-01')                                                            ,
  ('rosewood:ROSEWOOD-2026-06-0023', 63000, '2026-06-17 12:00:00', 'Rosewood seed 2026-06 · Sravan', 'ROSEWOOD-2026-06-0023', 'Sravan', '2026-06-01')                                                            ,
  ('rosewood:ROSEWOOD-2026-07-0024', 66000, '2026-07-18 12:00:00', 'Rosewood seed 2026-07 · Sravan', 'ROSEWOOD-2026-07-0024', 'Sravan', '2026-07-01')                                                            ,
  ('rosewood:ROSEWOOD-2026-06-0025', 88000, '2026-06-26 12:00:00', 'Rosewood seed 2026-06 · Chenxi Liu', 'ROSEWOOD-2026-06-0025', 'Chenxi Liu', '2026-06-01')                                                    ,
  ('rosewood:ROSEWOOD-2026-07-0026', 88000, '2026-07-01 12:00:00', 'Rosewood seed 2026-07 · Chenxi Liu', 'ROSEWOOD-2026-07-0026', 'Chenxi Liu', '2026-07-01')                                                    ,
  ('rosewood:ROSEWOOD-2026-08-0027', 88000, '2026-08-02 12:00:00', 'Rosewood seed 2026-08 · Chenxi Liu', 'ROSEWOOD-2026-08-0027', 'Chenxi Liu', '2026-08-01')                                                    ,
  ('rosewood:ROSEWOOD-2026-05-0028', 88000, '2026-05-23 12:00:00', 'Rosewood seed 2026-05 · Lilian', 'ROSEWOOD-2026-05-0028', 'Lilian', '2026-05-01')                                                            ,
  ('rosewood:ROSEWOOD-2026-05-0029', 50000, '2026-05-15 12:00:00', 'Rosewood seed 2026-05 · Bala Anush Choudhary', 'ROSEWOOD-2026-05-0029', 'Bala Anush Choudhary', '2026-05-01')                                ,
  ('rosewood:ROSEWOOD-2026-06-0030', 50000, '2026-06-16 12:00:00', 'Rosewood seed 2026-06 · Bala Anush Choudhary', 'ROSEWOOD-2026-06-0030', 'Bala Anush Choudhary', '2026-06-01')                                ,
  ('rosewood:ROSEWOOD-2026-07-0031', 50000, '2026-07-17 12:00:00', 'Rosewood seed 2026-07 · Bala Anush Choudhary', 'ROSEWOOD-2026-07-0031', 'Bala Anush Choudhary', '2026-07-01')                                ,
  ('rosewood:ROSEWOOD-2026-08-0032', 50000, '2026-08-18 12:00:00', 'Rosewood seed 2026-08 · Bala Anush Choudhary', 'ROSEWOOD-2026-08-0032', 'Bala Anush Choudhary', '2026-08-01')                                ,
  ('rosewood:ROSEWOOD-2026-05-0033', 50000, '2026-05-06 12:00:00', 'Rosewood seed 2026-05 · Hardik Gattu', 'ROSEWOOD-2026-05-0033', 'Hardik Gattu', '2026-05-01')                                                ,
  ('rosewood:ROSEWOOD-2026-06-0034', 50000, '2026-06-07 12:00:00', 'Rosewood seed 2026-06 · Hardik Gattu', 'ROSEWOOD-2026-06-0034', 'Hardik Gattu', '2026-06-01')                                                ,
  ('rosewood:ROSEWOOD-2026-07-0035', 50000, '2026-07-08 12:00:00', 'Rosewood seed 2026-07 · Hardik Gattu', 'ROSEWOOD-2026-07-0035', 'Hardik Gattu', '2026-07-01')                                                ,
  ('rosewood:ROSEWOOD-2026-08-0036', 50000, '2026-08-09 12:00:00', 'Rosewood seed 2026-08 · Hardik Gattu', 'ROSEWOOD-2026-08-0036', 'Hardik Gattu', '2026-08-01')                                                ,
  ('rosewood:ROSEWOOD-2026-09-0037', 50000, '2026-09-10 12:00:00', 'Rosewood seed 2026-09 · Hardik Gattu', 'ROSEWOOD-2026-09-0037', 'Hardik Gattu', '2026-09-01')                                                ,
  ('rosewood:ROSEWOOD-2026-05-0038', 50000, '2026-05-20 12:00:00', 'Rosewood seed 2026-05 · Priteesh Nandan', 'ROSEWOOD-2026-05-0038', 'Priteesh Nandan', '2026-05-01')                                          ,
  ('rosewood:ROSEWOOD-2026-06-0039', 50000, '2026-06-21 12:00:00', 'Rosewood seed 2026-06 · Priteesh Nandan', 'ROSEWOOD-2026-06-0039', 'Priteesh Nandan', '2026-06-01')                                          ,
  ('rosewood:ROSEWOOD-2026-07-0040', 50000, '2026-07-22 12:00:00', 'Rosewood seed 2026-07 · Priteesh Nandan', 'ROSEWOOD-2026-07-0040', 'Priteesh Nandan', '2026-07-01')                                          ,
  ('rosewood:ROSEWOOD-2026-08-0041', 50000, '2026-08-23 12:00:00', 'Rosewood seed 2026-08 · Priteesh Nandan', 'ROSEWOOD-2026-08-0041', 'Priteesh Nandan', '2026-08-01')                                          ,
  ('rosewood:ROSEWOOD-2026-09-0042', 50000, '2026-09-24 12:00:00', 'Rosewood seed 2026-09 · Priteesh Nandan', 'ROSEWOOD-2026-09-0042', 'Priteesh Nandan', '2026-09-01')                                          ,
  ('rosewood:ROSEWOOD-2026-07-0043', 68000, '2026-07-03 12:00:00', 'Rosewood seed 2026-07 · Devansh Chauhan', 'ROSEWOOD-2026-07-0043', 'Devansh Chauhan', '2026-07-01')                                          ,
  ('rosewood:ROSEWOOD-2026-08-0044', 68000, '2026-08-04 12:00:00', 'Rosewood seed 2026-08 · Devansh Chauhan', 'ROSEWOOD-2026-08-0044', 'Devansh Chauhan', '2026-08-01')                                          ,
  ('rosewood:ROSEWOOD-2026-09-0045', 68000, '2026-09-05 12:00:00', 'Rosewood seed 2026-09 · Devansh Chauhan', 'ROSEWOOD-2026-09-0045', 'Devansh Chauhan', '2026-09-01')                                          ,
  ('rosewood:ROSEWOOD-2026-05-0046', 68000, '2026-05-13 12:00:00', 'Rosewood seed 2026-05 · Noel Jose', 'ROSEWOOD-2026-05-0046', 'Noel Jose', '2026-05-01')                                                      ,
  ('rosewood:ROSEWOOD-2026-06-0047', 68000, '2026-06-14 12:00:00', 'Rosewood seed 2026-06 · Noel Jose', 'ROSEWOOD-2026-06-0047', 'Noel Jose', '2026-06-01')                                                      ,
  ('rosewood:ROSEWOOD-2026-07-0048', 68000, '2026-07-15 12:00:00', 'Rosewood seed 2026-07 · Noel Jose', 'ROSEWOOD-2026-07-0048', 'Noel Jose', '2026-07-01')                                                      ,
  ('rosewood:ROSEWOOD-2026-08-0049', 68000, '2026-08-16 12:00:00', 'Rosewood seed 2026-08 · Noel Jose', 'ROSEWOOD-2026-08-0049', 'Noel Jose', '2026-08-01')                                                      ,
  ('rosewood:ROSEWOOD-2026-09-0050', 68000, '2026-09-17 12:00:00', 'Rosewood seed 2026-09 · Noel Jose', 'ROSEWOOD-2026-09-0050', 'Noel Jose', '2026-09-01')                                                      ,
  ('rosewood:ROSEWOOD-2026-05-0051', 68000, '2026-05-01 12:00:00', 'Rosewood seed 2026-05 · Pavel Ionut Alexandru', 'ROSEWOOD-2026-05-0051', 'Pavel Ionut Alexandru', '2026-05-01')                              ,
  ('rosewood:ROSEWOOD-2026-06-0052', 63000, '2026-06-02 12:00:00', 'Rosewood seed 2026-06 · Pavel Ionut Alexandru', 'ROSEWOOD-2026-06-0052', 'Pavel Ionut Alexandru', '2026-06-01')                              ,
  ('rosewood:ROSEWOOD-2026-05-0053', 68000, '2026-05-23 12:00:00', 'Rosewood seed 2026-05 · Thant Lynn Htet', 'ROSEWOOD-2026-05-0053', 'Thant Lynn Htet', '2026-05-01')                                          ,
  ('rosewood:ROSEWOOD-2026-06-0054', 68000, '2026-06-24 12:00:00', 'Rosewood seed 2026-06 · Thant Lynn Htet', 'ROSEWOOD-2026-06-0054', 'Thant Lynn Htet', '2026-06-01')                                          ,
  ('rosewood:ROSEWOOD-2026-07-0055', 68000, '2026-07-25 12:00:00', 'Rosewood seed 2026-07 · Thant Lynn Htet', 'ROSEWOOD-2026-07-0055', 'Thant Lynn Htet', '2026-07-01')                                          ,
  ('rosewood:ROSEWOOD-2026-08-0056', 68000, '2026-08-26 12:00:00', 'Rosewood seed 2026-08 · Thant Lynn Htet', 'ROSEWOOD-2026-08-0056', 'Thant Lynn Htet', '2026-08-01')                                          ,
  ('rosewood:ROSEWOOD-2026-09-0057', 68000, '2026-09-01 12:00:00', 'Rosewood seed 2026-09 · Thant Lynn Htet', 'ROSEWOOD-2026-09-0057', 'Thant Lynn Htet', '2026-09-01')                                          ,
  ('rosewood:ROSEWOOD-2026-05-0058', 60000, '2026-05-06 12:00:00', 'Rosewood seed 2026-05 · Sai Chitraksh Amram', 'ROSEWOOD-2026-05-0058', 'Sai Chitraksh Amram', '2026-05-01')                                  ,
  ('rosewood:ROSEWOOD-2026-06-0059', 60000, '2026-06-07 12:00:00', 'Rosewood seed 2026-06 · Sai Chitraksh Amram', 'ROSEWOOD-2026-06-0059', 'Sai Chitraksh Amram', '2026-06-01')                                  ,
  ('rosewood:ROSEWOOD-2026-07-0060', 60000, '2026-07-11 12:00:00', 'Rosewood seed 2026-07 · Sriram Samala', 'ROSEWOOD-2026-07-0060', 'Sriram Samala', '2026-07-01')                                              ,
  ('rosewood:ROSEWOOD-2026-08-0061', 60000, '2026-08-12 12:00:00', 'Rosewood seed 2026-08 · Sriram Samala', 'ROSEWOOD-2026-08-0061', 'Sriram Samala', '2026-08-01')                                              ,
  ('rosewood:ROSEWOOD-2026-09-0062', 60000, '2026-09-13 12:00:00', 'Rosewood seed 2026-09 · Sriram Samala', 'ROSEWOOD-2026-09-0062', 'Sriram Samala', '2026-09-01')                                              ,
  ('rosewood:ROSEWOOD-2026-05-0063', 60000, '2026-05-15 12:00:00', 'Rosewood seed 2026-05 · Tajudin Shaik', 'ROSEWOOD-2026-05-0063', 'Tajudin Shaik', '2026-05-01')                                              ,
  ('rosewood:ROSEWOOD-2026-06-0064', 60000, '2026-06-16 12:00:00', 'Rosewood seed 2026-06 · Tajudin Shaik', 'ROSEWOOD-2026-06-0064', 'Tajudin Shaik', '2026-06-01')                                              ,
  ('rosewood:ROSEWOOD-2026-07-0065', 60000, '2026-07-17 12:00:00', 'Rosewood seed 2026-07 · Tajudin Shaik', 'ROSEWOOD-2026-07-0065', 'Tajudin Shaik', '2026-07-01')                                              ,
  ('rosewood:ROSEWOOD-2026-08-0066', 60000, '2026-08-18 12:00:00', 'Rosewood seed 2026-08 · Tajudin Shaik', 'ROSEWOOD-2026-08-0066', 'Tajudin Shaik', '2026-08-01')                                              ,
  ('rosewood:ROSEWOOD-2026-09-0067', 60000, '2026-09-19 12:00:00', 'Rosewood seed 2026-09 · Tajudin Shaik', 'ROSEWOOD-2026-09-0067', 'Tajudin Shaik', '2026-09-01')                                              ,
  ('rosewood:ROSEWOOD-2026-05-0068', 62500, '2026-05-06 12:00:00', 'Rosewood seed 2026-05 · Nghiem Duc Minh (Chris)', 'ROSEWOOD-2026-05-0068', 'Nghiem Duc Minh (Chris)', '2026-05-01')                          ,
  ('rosewood:ROSEWOOD-2026-06-0069', 56750, '2026-06-07 12:00:00', 'Rosewood seed 2026-06 · Nghiem Duc Minh (Chris)', 'ROSEWOOD-2026-06-0069', 'Nghiem Duc Minh (Chris)', '2026-06-01')                          ,
  ('rosewood:ROSEWOOD-2026-05-0070', 62500, '2026-05-05 12:00:00', 'Rosewood seed 2026-05 · Pham Trung Hieu (Harvey)', 'ROSEWOOD-2026-05-0070', 'Pham Trung Hieu (Harvey)', '2026-05-01')                        ,
  ('rosewood:ROSEWOOD-2026-06-0071', 56750, '2026-06-06 12:00:00', 'Rosewood seed 2026-06 · Pham Trung Hieu (Harvey)', 'ROSEWOOD-2026-06-0071', 'Pham Trung Hieu (Harvey)', '2026-06-01')                        ,
  ('rosewood:ROSEWOOD-2026-07-0072', 62500, '2026-07-25 12:00:00', 'Rosewood seed 2026-07 · Wahajullah Khan', 'ROSEWOOD-2026-07-0072', 'Wahajullah Khan', '2026-07-01')                                          ,
  ('rosewood:ROSEWOOD-2026-08-0073', 62500, '2026-08-26 12:00:00', 'Rosewood seed 2026-08 · Wahajullah Khan', 'ROSEWOOD-2026-08-0073', 'Wahajullah Khan', '2026-08-01')                                          ,
  ('rosewood:ROSEWOOD-2026-09-0074', 62500, '2026-09-01 12:00:00', 'Rosewood seed 2026-09 · Wahajullah Khan', 'ROSEWOOD-2026-09-0074', 'Wahajullah Khan', '2026-09-01')                                          ,
  ('rosewood:ROSEWOOD-2026-09-0075', 60000, '2026-09-24 12:00:00', 'Rosewood seed 2026-09 · Anish Kishor', 'ROSEWOOD-2026-09-0075', 'Anish Kishor', '2026-09-01')                                                ,
  ('rosewood:ROSEWOOD-2026-07-0076', 60000, '2026-07-12 12:00:00', 'Rosewood seed 2026-07 · Arslan Arshad', 'ROSEWOOD-2026-07-0076', 'Arslan Arshad', '2026-07-01')                                              ,
  ('rosewood:ROSEWOOD-2026-08-0077', 60000, '2026-08-13 12:00:00', 'Rosewood seed 2026-08 · Arslan Arshad', 'ROSEWOOD-2026-08-0077', 'Arslan Arshad', '2026-08-01')                                              ,
  ('rosewood:ROSEWOOD-2026-07-0078', 60000, '2026-07-05 12:00:00', 'Rosewood seed 2026-07 · Asad Raza', 'ROSEWOOD-2026-07-0078', 'Asad Raza', '2026-07-01')                                                      ,
  ('rosewood:ROSEWOOD-2026-08-0079', 60000, '2026-08-06 12:00:00', 'Rosewood seed 2026-08 · Asad Raza', 'ROSEWOOD-2026-08-0079', 'Asad Raza', '2026-08-01')                                                      ,
  ('rosewood:ROSEWOOD-2026-05-0080', 60000, '2026-05-23 12:00:00', 'Rosewood seed 2026-05 · Chu Sandy Kyaw', 'ROSEWOOD-2026-05-0080', 'Chu Sandy Kyaw', '2026-05-01')                                            ,
  ('rosewood:ROSEWOOD-2026-06-0081', 60000, '2026-06-24 12:00:00', 'Rosewood seed 2026-06 · Chu Sandy Kyaw', 'ROSEWOOD-2026-06-0081', 'Chu Sandy Kyaw', '2026-06-01')                                            ,
  ('rosewood:ROSEWOOD-2026-09-0082', 60000, '2026-09-09 12:00:00', 'Rosewood seed 2026-09 · Henisha Anish Raut', 'ROSEWOOD-2026-09-0082', 'Henisha Anish Raut', '2026-09-01')                                    ,
  ('rosewood:ROSEWOOD-2026-05-0083', 60000, '2026-05-15 12:00:00', 'Rosewood seed 2026-05 · Wai Aung', 'ROSEWOOD-2026-05-0083', 'Wai Aung', '2026-05-01')                                                        ,
  ('rosewood:ROSEWOOD-2026-06-0084', 60000, '2026-06-16 12:00:00', 'Rosewood seed 2026-06 · Wai Aung', 'ROSEWOOD-2026-06-0084', 'Wai Aung', '2026-06-01')                                                        ,
  ('rosewood:ROSEWOOD-2026-07-0085', 60000, '2026-07-15 12:00:00', 'Rosewood seed 2026-07 · Ananya M', 'ROSEWOOD-2026-07-0085', 'Ananya M', '2026-07-01')                                                        ,
  ('rosewood:ROSEWOOD-2026-08-0086', 60000, '2026-08-16 12:00:00', 'Rosewood seed 2026-08 · Ananya M', 'ROSEWOOD-2026-08-0086', 'Ananya M', '2026-08-01')                                                        ,
  ('rosewood:ROSEWOOD-2026-05-0087', 60000, '2026-05-19 12:00:00', 'Rosewood seed 2026-05 · Min Myat Moe', 'ROSEWOOD-2026-05-0087', 'Min Myat Moe', '2026-05-01')                                                ,
  ('rosewood:ROSEWOOD-2026-06-0088', 60000, '2026-06-20 12:00:00', 'Rosewood seed 2026-06 · Min Myat Moe', 'ROSEWOOD-2026-06-0088', 'Min Myat Moe', '2026-06-01')                                                ,
  ('rosewood:ROSEWOOD-2026-05-0089', 60000, '2026-05-16 12:00:00', 'Rosewood seed 2026-05 · Nyan Lin Htut', 'ROSEWOOD-2026-05-0089', 'Nyan Lin Htut', '2026-05-01')                                              ,
  ('rosewood:ROSEWOOD-2026-06-0090', 60000, '2026-06-17 12:00:00', 'Rosewood seed 2026-06 · Nyan Lin Htut', 'ROSEWOOD-2026-06-0090', 'Nyan Lin Htut', '2026-06-01')                                              ,
  ('rosewood:ROSEWOOD-2026-07-0091', 60000, '2026-07-02 12:00:00', 'Rosewood seed 2026-07 · Satvik Talawar', 'ROSEWOOD-2026-07-0091', 'Satvik Talawar', '2026-07-01')                                            ,
  ('rosewood:ROSEWOOD-2026-08-0092', 60000, '2026-08-03 12:00:00', 'Rosewood seed 2026-08 · Satvik Talawar', 'ROSEWOOD-2026-08-0092', 'Satvik Talawar', '2026-08-01')                                            ,
  ('rosewood:ROSEWOOD-2026-09-0093', 60000, '2026-09-04 12:00:00', 'Rosewood seed 2026-09 · Satvik Talawar', 'ROSEWOOD-2026-09-0093', 'Satvik Talawar', '2026-09-01')                                            ,
  ('rosewood:ROSEWOOD-2026-05-0094', 70000, '2026-05-19 12:00:00', 'Rosewood seed 2026-05 · Abhishek Bhagwat', 'ROSEWOOD-2026-05-0094', 'Abhishek Bhagwat', '2026-05-01')                                        ,
  ('rosewood:ROSEWOOD-2026-06-0095', 70000, '2026-06-20 12:00:00', 'Rosewood seed 2026-06 · Abhishek Bhagwat', 'ROSEWOOD-2026-06-0095', 'Abhishek Bhagwat', '2026-06-01')                                        ,
  ('rosewood:ROSEWOOD-2026-07-0096', 70000, '2026-07-17 12:00:00', 'Rosewood seed 2026-07 · Eider Esneir', 'ROSEWOOD-2026-07-0096', 'Eider Esneir', '2026-07-01')                                                ,
  ('rosewood:ROSEWOOD-2026-08-0097', 70000, '2026-08-18 12:00:00', 'Rosewood seed 2026-08 · Eider Esneir', 'ROSEWOOD-2026-08-0097', 'Eider Esneir', '2026-08-01')                                                ,
  ('rosewood:ROSEWOOD-2026-09-0098', 70000, '2026-09-19 12:00:00', 'Rosewood seed 2026-09 · Eider Esneir', 'ROSEWOOD-2026-09-0098', 'Eider Esneir', '2026-09-01')                                                ,
  ('rosewood:ROSEWOOD-2026-05-0099', 58000, '2026-05-23 12:00:00', 'Rosewood seed 2026-05 · Ardra M Punathil', 'ROSEWOOD-2026-05-0099', 'Ardra M Punathil', '2026-05-01')                                        ,
  ('rosewood:ROSEWOOD-2026-06-0100', 58000, '2026-06-24 12:00:00', 'Rosewood seed 2026-06 · Ardra M Punathil', 'ROSEWOOD-2026-06-0100', 'Ardra M Punathil', '2026-06-01')                                        ,
  ('rosewood:ROSEWOOD-2026-07-0101', 58000, '2026-07-25 12:00:00', 'Rosewood seed 2026-07 · Ardra M Punathil', 'ROSEWOOD-2026-07-0101', 'Ardra M Punathil', '2026-07-01')                                        ,
  ('rosewood:ROSEWOOD-2026-08-0102', 58000, '2026-08-26 12:00:00', 'Rosewood seed 2026-08 · Ardra M Punathil', 'ROSEWOOD-2026-08-0102', 'Ardra M Punathil', '2026-08-01')                                        ,
  ('rosewood:ROSEWOOD-2026-09-0103', 58000, '2026-09-01 12:00:00', 'Rosewood seed 2026-09 · Ardra M Punathil', 'ROSEWOOD-2026-09-0103', 'Ardra M Punathil', '2026-09-01')                                        ,
  ('rosewood:ROSEWOOD-2026-05-0104', 58000, '2026-05-09 12:00:00', 'Rosewood seed 2026-05 · Meghana Vipin Mehta', 'ROSEWOOD-2026-05-0104', 'Meghana Vipin Mehta', '2026-05-01')                                  ,
  ('rosewood:ROSEWOOD-2026-06-0105', 58000, '2026-06-10 12:00:00', 'Rosewood seed 2026-06 · Meghana Vipin Mehta', 'ROSEWOOD-2026-06-0105', 'Meghana Vipin Mehta', '2026-06-01')                                  ,
  ('rosewood:ROSEWOOD-2026-07-0106', 58000, '2026-07-11 12:00:00', 'Rosewood seed 2026-07 · Meghana Vipin Mehta', 'ROSEWOOD-2026-07-0106', 'Meghana Vipin Mehta', '2026-07-01')                                  ,
  ('rosewood:ROSEWOOD-2026-08-0107', 58000, '2026-08-12 12:00:00', 'Rosewood seed 2026-08 · Meghana Vipin Mehta', 'ROSEWOOD-2026-08-0107', 'Meghana Vipin Mehta', '2026-08-01')                                  ,
  ('rosewood:ROSEWOOD-2026-09-0108', 58000, '2026-09-13 12:00:00', 'Rosewood seed 2026-09 · Meghana Vipin Mehta', 'ROSEWOOD-2026-09-0108', 'Meghana Vipin Mehta', '2026-09-01')                                  ,
  ('rosewood:ROSEWOOD-2026-05-0109', 60000, '2026-05-11 12:00:00', 'Rosewood seed 2026-05 · Avila Almeida', 'ROSEWOOD-2026-05-0109', 'Avila Almeida', '2026-05-01')                                              ,
  ('rosewood:ROSEWOOD-2026-06-0110', 60000, '2026-06-12 12:00:00', 'Rosewood seed 2026-06 · Avila Almeida', 'ROSEWOOD-2026-06-0110', 'Avila Almeida', '2026-06-01')                                              ,
  ('rosewood:ROSEWOOD-2026-07-0111', 60000, '2026-07-13 12:00:00', 'Rosewood seed 2026-07 · Avila Almeida', 'ROSEWOOD-2026-07-0111', 'Avila Almeida', '2026-07-01')                                              ,
  ('rosewood:ROSEWOOD-2026-05-0112', 60000, '2026-05-10 12:00:00', 'Rosewood seed 2026-05 · Blancy Mendes', 'ROSEWOOD-2026-05-0112', 'Blancy Mendes', '2026-05-01')                                              ,
  ('rosewood:ROSEWOOD-2026-06-0113', 60000, '2026-06-11 12:00:00', 'Rosewood seed 2026-06 · Blancy Mendes', 'ROSEWOOD-2026-06-0113', 'Blancy Mendes', '2026-06-01')                                              ,
  ('rosewood:ROSEWOOD-2026-09-0114', 60000, '2026-09-26 12:00:00', 'Rosewood seed 2026-09 · Domingo Jose Cristo Sanches', 'ROSEWOOD-2026-09-0114', 'Domingo Jose Cristo Sanches', '2026-09-01')                  ,
  ('rosewood:ROSEWOOD-2026-07-0115', 61000, '2026-07-26 12:00:00', 'Rosewood seed 2026-07 · Durga Nagendra', 'ROSEWOOD-2026-07-0115', 'Durga Nagendra', '2026-07-01')                                            ,
  ('rosewood:ROSEWOOD-2026-08-0116', 61000, '2026-08-01 12:00:00', 'Rosewood seed 2026-08 · Durga Nagendra', 'ROSEWOOD-2026-08-0116', 'Durga Nagendra', '2026-08-01')                                            ,
  ('rosewood:ROSEWOOD-2026-09-0117', 61000, '2026-09-02 12:00:00', 'Rosewood seed 2026-09 · Durga Nagendra', 'ROSEWOOD-2026-09-0117', 'Durga Nagendra', '2026-09-01')                                            ,
  ('rosewood:ROSEWOOD-2026-07-0118', 61000, '2026-07-18 12:00:00', 'Rosewood seed 2026-07 · Lohit Dinesh', 'ROSEWOOD-2026-07-0118', 'Lohit Dinesh', '2026-07-01')                                                ,
  ('rosewood:ROSEWOOD-2026-08-0119', 61000, '2026-08-19 12:00:00', 'Rosewood seed 2026-08 · Lohit Dinesh', 'ROSEWOOD-2026-08-0119', 'Lohit Dinesh', '2026-08-01')                                                ,
  ('rosewood:ROSEWOOD-2026-09-0120', 61000, '2026-09-20 12:00:00', 'Rosewood seed 2026-09 · Lohit Dinesh', 'ROSEWOOD-2026-09-0120', 'Lohit Dinesh', '2026-09-01')                                                ,
  ('rosewood:ROSEWOOD-2026-05-0121', 61000, '2026-05-22 12:00:00', 'Rosewood seed 2026-05 · Nagendra Gonugunta', 'ROSEWOOD-2026-05-0121', 'Nagendra Gonugunta', '2026-05-01')                                    ,
  ('rosewood:ROSEWOOD-2026-06-0122', 61000, '2026-06-23 12:00:00', 'Rosewood seed 2026-06 · Nagendra Gonugunta', 'ROSEWOOD-2026-06-0122', 'Nagendra Gonugunta', '2026-06-01')                                    ,
  ('rosewood:ROSEWOOD-2026-05-0123', 61000, '2026-05-20 12:00:00', 'Rosewood seed 2026-05 · Raj', 'ROSEWOOD-2026-05-0123', 'Raj', '2026-05-01')                                                                  ,
  ('rosewood:ROSEWOOD-2026-06-0124', 61000, '2026-06-21 12:00:00', 'Rosewood seed 2026-06 · Raj', 'ROSEWOOD-2026-06-0124', 'Raj', '2026-06-01')                                                                  ,
  ('rosewood:ROSEWOOD-2026-05-0125', 49500, '2026-05-23 12:00:00', 'Rosewood seed 2026-05 · Amal Surya', 'ROSEWOOD-2026-05-0125', 'Amal Surya', '2026-05-01')                                                    ,
  ('rosewood:ROSEWOOD-2026-06-0126', 49500, '2026-06-24 12:00:00', 'Rosewood seed 2026-06 · Amal Surya', 'ROSEWOOD-2026-06-0126', 'Amal Surya', '2026-06-01')                                                    ,
  ('rosewood:ROSEWOOD-2026-07-0127', 49500, '2026-07-25 12:00:00', 'Rosewood seed 2026-07 · Amal Surya', 'ROSEWOOD-2026-07-0127', 'Amal Surya', '2026-07-01')                                                    ,
  ('rosewood:ROSEWOOD-2026-08-0128', 49500, '2026-08-26 12:00:00', 'Rosewood seed 2026-08 · Amal Surya', 'ROSEWOOD-2026-08-0128', 'Amal Surya', '2026-08-01')                                                    ,
  ('rosewood:ROSEWOOD-2026-09-0129', 49500, '2026-09-01 12:00:00', 'Rosewood seed 2026-09 · Amal Surya', 'ROSEWOOD-2026-09-0129', 'Amal Surya', '2026-09-01')                                                    ,
  ('rosewood:ROSEWOOD-2026-05-0130', 49500, '2026-05-20 12:00:00', 'Rosewood seed 2026-05 · Rohith Murali', 'ROSEWOOD-2026-05-0130', 'Rohith Murali', '2026-05-01')                                              ,
  ('rosewood:ROSEWOOD-2026-06-0131', 49500, '2026-06-21 12:00:00', 'Rosewood seed 2026-06 · Rohith Murali', 'ROSEWOOD-2026-06-0131', 'Rohith Murali', '2026-06-01')                                              ,
  ('rosewood:ROSEWOOD-2026-07-0132', 49500, '2026-07-08 12:00:00', 'Rosewood seed 2026-07 · Suryakarthik', 'ROSEWOOD-2026-07-0132', 'Suryakarthik', '2026-07-01')                                                ,
  ('rosewood:ROSEWOOD-2026-08-0133', 49500, '2026-08-09 12:00:00', 'Rosewood seed 2026-08 · Suryakarthik', 'ROSEWOOD-2026-08-0133', 'Suryakarthik', '2026-08-01')                                                ,
  ('rosewood:ROSEWOOD-2026-09-0134', 49500, '2026-09-10 12:00:00', 'Rosewood seed 2026-09 · Suryakarthik', 'ROSEWOOD-2026-09-0134', 'Suryakarthik', '2026-09-01')                                                ,
  ('rosewood:ROSEWOOD-2026-05-0135', 73000, '2026-05-09 12:00:00', 'Rosewood seed 2026-05 · Bhuvaneswaran', 'ROSEWOOD-2026-05-0135', 'Bhuvaneswaran', '2026-05-01')                                              ,
  ('rosewood:ROSEWOOD-2026-06-0136', 73000, '2026-06-10 12:00:00', 'Rosewood seed 2026-06 · Bhuvaneswaran', 'ROSEWOOD-2026-06-0136', 'Bhuvaneswaran', '2026-06-01')                                              ,
  ('rosewood:ROSEWOOD-2026-07-0137', 73000, '2026-07-25 12:00:00', 'Rosewood seed 2026-07 · Kaushik Kannan', 'ROSEWOOD-2026-07-0137', 'Kaushik Kannan', '2026-07-01')                                            ,
  ('rosewood:ROSEWOOD-2026-08-0138', 73000, '2026-08-26 12:00:00', 'Rosewood seed 2026-08 · Kaushik Kannan', 'ROSEWOOD-2026-08-0138', 'Kaushik Kannan', '2026-08-01')                                            ,
  ('rosewood:ROSEWOOD-2026-09-0139', 73000, '2026-09-01 12:00:00', 'Rosewood seed 2026-09 · Kaushik Kannan', 'ROSEWOOD-2026-09-0139', 'Kaushik Kannan', '2026-09-01')                                            ,
  ('rosewood:ROSEWOOD-2026-07-0140', 73000, '2026-07-02 12:00:00', 'Rosewood seed 2026-07 · Bhuvaneswaran', 'ROSEWOOD-2026-07-0140', 'Bhuvaneswaran', '2026-07-01')                                              ,
  ('rosewood:ROSEWOOD-2026-08-0141', 73000, '2026-08-03 12:00:00', 'Rosewood seed 2026-08 · Bhuvaneswaran', 'ROSEWOOD-2026-08-0141', 'Bhuvaneswaran', '2026-08-01')                                              ,
  ('rosewood:ROSEWOOD-2026-09-0142', 73000, '2026-09-04 12:00:00', 'Rosewood seed 2026-09 · Bhuvaneswaran', 'ROSEWOOD-2026-09-0142', 'Bhuvaneswaran', '2026-09-01')                                              ,
  ('rosewood:ROSEWOOD-2026-05-0143', 73000, '2026-05-11 12:00:00', 'Rosewood seed 2026-05 · Kaushik Kannan', 'ROSEWOOD-2026-05-0143', 'Kaushik Kannan', '2026-05-01')                                            ,
  ('rosewood:ROSEWOOD-2026-06-0144', 73000, '2026-06-12 12:00:00', 'Rosewood seed 2026-06 · Kaushik Kannan', 'ROSEWOOD-2026-06-0144', 'Kaushik Kannan', '2026-06-01')                                            ,
  ('rosewood:ROSEWOOD-2026-05-0145', 79000, '2026-05-14 12:00:00', 'Rosewood seed 2026-05 · Ajay Pandikasala', 'ROSEWOOD-2026-05-0145', 'Ajay Pandikasala', '2026-05-01')                                        ,
  ('rosewood:ROSEWOOD-2026-06-0146', 79000, '2026-06-15 12:00:00', 'Rosewood seed 2026-06 · Ajay Pandikasala', 'ROSEWOOD-2026-06-0146', 'Ajay Pandikasala', '2026-06-01')                                        ,
  ('rosewood:ROSEWOOD-2026-07-0147', 79000, '2026-07-16 12:00:00', 'Rosewood seed 2026-07 · Ajay Pandikasala', 'ROSEWOOD-2026-07-0147', 'Ajay Pandikasala', '2026-07-01')                                        ,
  ('rosewood:ROSEWOOD-2026-08-0148', 79000, '2026-08-17 12:00:00', 'Rosewood seed 2026-08 · Ajay Pandikasala', 'ROSEWOOD-2026-08-0148', 'Ajay Pandikasala', '2026-08-01')                                        ,
  ('rosewood:ROSEWOOD-2026-05-0149', 60000, '2026-05-23 12:00:00', 'Rosewood seed 2026-05 · Yong Liu', 'ROSEWOOD-2026-05-0149', 'Yong Liu', '2026-05-01')                                                        ,
  ('rosewood:ROSEWOOD-2026-06-0150', 60000, '2026-06-24 12:00:00', 'Rosewood seed 2026-06 · Yong Liu', 'ROSEWOOD-2026-06-0150', 'Yong Liu', '2026-06-01')                                                        ,
  ('rosewood:ROSEWOOD-2026-07-0151', 60000, '2026-07-25 12:00:00', 'Rosewood seed 2026-07 · Yong Liu', 'ROSEWOOD-2026-07-0151', 'Yong Liu', '2026-07-01')                                                        ,
  ('rosewood:ROSEWOOD-2026-08-0152', 60000, '2026-08-26 12:00:00', 'Rosewood seed 2026-08 · Yong Liu', 'ROSEWOOD-2026-08-0152', 'Yong Liu', '2026-08-01')                                                        ,
  ('rosewood:ROSEWOOD-2026-09-0153', 55000, '2026-09-01 12:00:00', 'Rosewood seed 2026-09 · Yong Liu', 'ROSEWOOD-2026-09-0153', 'Yong Liu', '2026-09-01')                                                        ,
  ('rosewood:ROSEWOOD-2026-05-0154', 90000, '2026-05-24 12:00:00', 'Rosewood seed 2026-05 · Abdulrahman Elfeky', 'ROSEWOOD-2026-05-0154', 'Abdulrahman Elfeky', '2026-05-01')                                    ,
  ('rosewood:ROSEWOOD-2026-06-0155', 90000, '2026-06-25 12:00:00', 'Rosewood seed 2026-06 · Abdulrahman Elfeky', 'ROSEWOOD-2026-06-0155', 'Abdulrahman Elfeky', '2026-06-01')                                    ,
  ('rosewood:ROSEWOOD-2026-07-0156', 90000, '2026-07-26 12:00:00', 'Rosewood seed 2026-07 · Abdulrahman Elfeky', 'ROSEWOOD-2026-07-0156', 'Abdulrahman Elfeky', '2026-07-01')                                    ,
  ('rosewood:ROSEWOOD-2026-08-0157', 90000, '2026-08-01 12:00:00', 'Rosewood seed 2026-08 · Abdulrahman Elfeky', 'ROSEWOOD-2026-08-0157', 'Abdulrahman Elfeky', '2026-08-01')                                    ,
  ('rosewood:ROSEWOOD-2026-09-0158', 90000, '2026-09-02 12:00:00', 'Rosewood seed 2026-09 · Abdulrahman Elfeky', 'ROSEWOOD-2026-09-0158', 'Abdulrahman Elfeky', '2026-09-01')                                    ,
  ('rosewood:ROSEWOOD-2026-05-0159', 62500, '2026-05-16 12:00:00', 'Rosewood seed 2026-05 · Gleice Cristina Rodrigues da Silva', 'ROSEWOOD-2026-05-0159', 'Gleice Cristina Rodrigues da Silva', '2026-05-01')    ,
  ('rosewood:ROSEWOOD-2026-06-0160', 62500, '2026-06-17 12:00:00', 'Rosewood seed 2026-06 · Gleice Cristina Rodrigues da Silva', 'ROSEWOOD-2026-06-0160', 'Gleice Cristina Rodrigues da Silva', '2026-06-01')    ,
  ('rosewood:ROSEWOOD-2026-07-0161', 62500, '2026-07-18 12:00:00', 'Rosewood seed 2026-07 · Gleice Cristina Rodrigues da Silva', 'ROSEWOOD-2026-07-0161', 'Gleice Cristina Rodrigues da Silva', '2026-07-01')    ,
  ('rosewood:ROSEWOOD-2026-08-0162', 62500, '2026-08-19 12:00:00', 'Rosewood seed 2026-08 · Gleice Cristina Rodrigues da Silva', 'ROSEWOOD-2026-08-0162', 'Gleice Cristina Rodrigues da Silva', '2026-08-01')    ,
  ('rosewood:ROSEWOOD-2026-09-0163', 62500, '2026-09-20 12:00:00', 'Rosewood seed 2026-09 · Gleice Cristina Rodrigues da Silva', 'ROSEWOOD-2026-09-0163', 'Gleice Cristina Rodrigues da Silva', '2026-09-01')    ,
  ('rosewood:ROSEWOOD-2026-05-0164', 62500, '2026-05-12 12:00:00', 'Rosewood seed 2026-05 · Vitor Hugo Silva Carvalho', 'ROSEWOOD-2026-05-0164', 'Vitor Hugo Silva Carvalho', '2026-05-01')                      ,
  ('rosewood:ROSEWOOD-2026-06-0165', 62500, '2026-06-13 12:00:00', 'Rosewood seed 2026-06 · Vitor Hugo Silva Carvalho', 'ROSEWOOD-2026-06-0165', 'Vitor Hugo Silva Carvalho', '2026-06-01')                      ,
  ('rosewood:ROSEWOOD-2026-07-0166', 62500, '2026-07-14 12:00:00', 'Rosewood seed 2026-07 · Vitor Hugo Silva Carvalho', 'ROSEWOOD-2026-07-0166', 'Vitor Hugo Silva Carvalho', '2026-07-01')                      ,
  ('rosewood:ROSEWOOD-2026-08-0167', 62500, '2026-08-15 12:00:00', 'Rosewood seed 2026-08 · Vitor Hugo Silva Carvalho', 'ROSEWOOD-2026-08-0167', 'Vitor Hugo Silva Carvalho', '2026-08-01')                      ,
  ('rosewood:ROSEWOOD-2026-09-0168', 62500, '2026-09-16 12:00:00', 'Rosewood seed 2026-09 · Vitor Hugo Silva Carvalho', 'ROSEWOOD-2026-09-0168', 'Vitor Hugo Silva Carvalho', '2026-09-01')                      ,
  ('rosewood:ROSEWOOD-2026-05-0169', 80000, '2026-05-04 12:00:00', 'Rosewood seed 2026-05 · Rafael de Souza Santos Cunha', 'ROSEWOOD-2026-05-0169', 'Rafael de Souza Santos Cunha', '2026-05-01')                ,
  ('rosewood:ROSEWOOD-2026-06-0170', 40000, '2026-06-05 12:00:00', 'Rosewood seed 2026-06 · Rafael de Souza Santos Cunha', 'ROSEWOOD-2026-06-0170', 'Rafael de Souza Santos Cunha', '2026-06-01')                ,
  ('rosewood:ROSEWOOD-2026-07-0171', 80000, '2026-07-06 12:00:00', 'Rosewood seed 2026-07 · Rafael de Souza Santos Cunha', 'ROSEWOOD-2026-07-0171', 'Rafael de Souza Santos Cunha', '2026-07-01')                ,
  ('rosewood:ROSEWOOD-2026-08-0172', 80000, '2026-08-07 12:00:00', 'Rosewood seed 2026-08 · Rafael de Souza Santos Cunha', 'ROSEWOOD-2026-08-0172', 'Rafael de Souza Santos Cunha', '2026-08-01')                ,
  ('rosewood:ROSEWOOD-2026-09-0173', 80000, '2026-09-08 12:00:00', 'Rosewood seed 2026-09 · Rafael de Souza Santos Cunha', 'ROSEWOOD-2026-09-0173', 'Rafael de Souza Santos Cunha', '2026-09-01')                ,
  ('rosewood:ROSEWOOD-2026-05-0174', 45000, '2026-05-09 12:00:00', 'Rosewood seed 2026-05 · Atif Anam', 'ROSEWOOD-2026-05-0174', 'Atif Anam', '2026-05-01')                                                      ,
  ('rosewood:ROSEWOOD-2026-06-0175', 65000, '2026-06-10 12:00:00', 'Rosewood seed 2026-06 · Atif Anam', 'ROSEWOOD-2026-06-0175', 'Atif Anam', '2026-06-01')                                                      ,
  ('rosewood:ROSEWOOD-2026-07-0176', 30000, '2026-07-11 12:00:00', 'Rosewood seed 2026-07 · Atif Anam', 'ROSEWOOD-2026-07-0176', 'Atif Anam', '2026-07-01')                                                      ,
  ('rosewood:ROSEWOOD-2026-08-0177', 65000, '2026-08-12 12:00:00', 'Rosewood seed 2026-08 · Atif Anam', 'ROSEWOOD-2026-08-0177', 'Atif Anam', '2026-08-01')                                                      ,
  ('rosewood:ROSEWOOD-2026-09-0178', 65000, '2026-09-13 12:00:00', 'Rosewood seed 2026-09 · Atif Anam', 'ROSEWOOD-2026-09-0178', 'Atif Anam', '2026-09-01')                                                      ,
  ('rosewood:ROSEWOOD-2026-06-0179', 65000, '2026-06-12 12:00:00', 'Rosewood seed 2026-06 · Mohd Anamul Haq', 'ROSEWOOD-2026-06-0179', 'Mohd Anamul Haq', '2026-06-01')                                          ,
  ('rosewood:ROSEWOOD-2026-07-0180', 65000, '2026-07-13 12:00:00', 'Rosewood seed 2026-07 · Mohd Anamul Haq', 'ROSEWOOD-2026-07-0180', 'Mohd Anamul Haq', '2026-07-01')                                          ,
  ('rosewood:ROSEWOOD-2026-08-0181', 65000, '2026-08-14 12:00:00', 'Rosewood seed 2026-08 · Mohd Anamul Haq', 'ROSEWOOD-2026-08-0181', 'Mohd Anamul Haq', '2026-08-01')                                          ,
  ('rosewood:ROSEWOOD-2026-09-0182', 65000, '2026-09-15 12:00:00', 'Rosewood seed 2026-09 · Mohd Anamul Haq', 'ROSEWOOD-2026-09-0182', 'Mohd Anamul Haq', '2026-09-01')                                          ,
  ('rosewood:ROSEWOOD-2026-05-0183', 120000, '2026-05-08 12:00:00', 'Rosewood seed 2026-05 · Qiang Li', 'ROSEWOOD-2026-05-0183', 'Qiang Li', '2026-05-01')                                                       ,
  ('rosewood:ROSEWOOD-2026-06-0184', 120000, '2026-06-09 12:00:00', 'Rosewood seed 2026-06 · Qiang Li', 'ROSEWOOD-2026-06-0184', 'Qiang Li', '2026-06-01')                                                       ,
  ('rosewood:ROSEWOOD-2026-07-0185', 120000, '2026-07-10 12:00:00', 'Rosewood seed 2026-07 · Qiang Li', 'ROSEWOOD-2026-07-0185', 'Qiang Li', '2026-07-01')                                                       ,
  ('rosewood:ROSEWOOD-2026-08-0186', 120000, '2026-08-11 12:00:00', 'Rosewood seed 2026-08 · Qiang Li', 'ROSEWOOD-2026-08-0186', 'Qiang Li', '2026-08-01')                                                       ;
DROP TEMPORARY TABLE IF EXISTS _rs_payer;
CREATE TEMPORARY TABLE _rs_payer (
  tenant_key varchar(64) NOT NULL PRIMARY KEY,
  payer_name varchar(191) NOT NULL,
  payer_name_normalized varchar(191) NOT NULL
) ENGINE=InnoDB;
INSERT INTO _rs_payer (tenant_key, payer_name, payer_name_normalized) VALUES
  ('kimmage-01-anselmo-2026-05', 'Anselmo Augusto dos Santos Rodrigues', 'anselmo augusto dos santos rodrigues'),
  ('kimmage-02-chidera-2026-05', 'Chidera Nnaeto', 'chidera nnaeto')                                            ,
  ('kimmage-02-siddarth-2026-05', 'Siddarth Janagouda', 'siddarth janagouda')                                   ,
  ('kimmage-03-abdellatif-2026-09', 'Abdellatif', 'abdellatif')                                                 ,
  ('kimmage-03-neil-2026-05', 'Neil Jose', 'neil jose')                                                         ,
  ('kimmage-03-sravan-2026-05', 'Sravan', 'sravan')                                                             ,
  ('kimmage-05-anush-2026-05', 'Bala Anush Choudhary', 'bala anush choudhary')                                  ,
  ('kimmage-06-noel-2026-05', 'Noel Jose', 'noel jose')                                                         ,
  ('kimmage-06-pavel-2026-05', 'Pavel Ionut Alexandru', 'pavel ionut alexandru')                                ,
  ('oldcounty-1-thant-2026-05', 'Thant Lynn Htet', 'thant lynn htet')                                           ,
  ('oldcounty-2-sriram-2026-07', 'Sriram Samala', 'sriram samala')                                              ,
  ('oldcounty-2-tajudin-2026-05', 'Tajudin Shaik', 'tajudin shaik')                                             ,
  ('oldcounty-3-nghiem-2026-05', 'Nghiem Duc Minh (Chris)', 'nghiem duc minh (chris)')                          ,
  ('oldcounty-3-pham-2026-05', 'Pham Trung Hieu (Harvey)', 'pham trung hieu (harvey)')                          ,
  ('oldcounty-4-arslan-2026-07', 'Arslan Arshad', 'arslan arshad')                                              ,
  ('oldcounty-4-asad-2026-07', 'Asad Raza', 'asad raza')                                                        ,
  ('oldcounty-4-wai-2026-05', 'Wai Aung', 'wai aung')                                                           ,
  ('walkinstown-2-ardra-2026-05', 'Ardra M Punathil', 'ardra m punathil')                                       ,
  ('walkinstown-2-meghana-2026-05', 'Meghana Vipin Mehta', 'meghana vipin mehta')                               ,
  ('walkinstown-3-blancy-2026-05', 'Blancy Mendes', 'blancy mendes')                                            ,
  ('walkinstown-4-durga-2026-07', 'Durga Nagendra', 'durga nagendra')                                           ,
  ('walkinstown-4-lohit-2026-07', 'Lohit Dinesh', 'lohit dinesh')                                               ,
  ('walkinstown-4-raj-2026-05', 'Raj', 'raj')                                                                   ,
  ('walkinstown-5-amal-2026-05', 'Amal Surya', 'amal surya')                                                    ,
  ('walkinstown-5-suryakarthik-2026-07', 'Suryakarthik', 'suryakarthik')                                        ,
  ('walkinstown-8-ajay-2026-05', 'Ajay Pandikasala', 'ajay pandikasala')                                        ,
  ('windmill-01-yong-2026-05', 'Yong Liu', 'yong liu')                                                          ,
  ('windmill-03-gleice-2026-05', 'Gleice Cristina Rodrigues da Silva', 'gleice cristina rodrigues da silva')    ,
  ('windmill-04-rafael-2026-05', 'Rafael de Souza Santos Cunha', 'rafael de souza santos cunha')                ,
  ('windmill-05-atif-2026-05', 'Atif Anam', 'atif anam')                                                        ,
  ('windmill-05-mohd-2026-06', 'Mohd Anamul Haq', 'mohd anamul haq')                                            ;

START TRANSACTION;

-- 2) delete exactly this seed's rows, children before parents
--    (fk_rooms_property, fk_tenancy_agreements_room, fk_agreement_parties_*
--     and fk_rent_obligations_charge are RESTRICT, so order matters)
DELETE pa FROM payment_allocations pa
  JOIN payment_transactions pt ON pt.id = pa.payment_transaction_id
 WHERE pt.user_id = @uid AND pt.stable_transaction_key LIKE 'rosewood:%';
DELETE cr FROM cash_receipts cr
  JOIN payment_transactions pt ON pt.id = cr.payment_transaction_id
 WHERE pt.user_id = @uid AND pt.stable_transaction_key LIKE 'rosewood:%';
DELETE act FROM payment_transaction_actions act
  JOIN payment_transactions pt ON pt.id = act.payment_transaction_id
 WHERE pt.user_id = @uid AND pt.stable_transaction_key LIKE 'rosewood:%';
DELETE FROM payment_transactions WHERE user_id = @uid AND stable_transaction_key LIKE 'rosewood:%';

DELETE ap FROM agreement_parties ap
  JOIN tenancy_agreements ta ON ta.id = ap.agreement_id
  JOIN rooms r ON r.id = ta.room_id
  JOIN properties p ON p.id = r.property_id
  JOIN _rs_property k ON k.name = p.name
 WHERE ap.user_id = @uid AND p.user_id = @uid;
DELETE ta FROM tenancy_agreements ta
  JOIN rooms r ON r.id = ta.room_id
  JOIN properties p ON p.id = r.property_id
  JOIN _rs_property k ON k.name = p.name
 WHERE ta.user_id = @uid AND p.user_id = @uid;

DELETE o FROM rent_obligations o
  JOIN tenants t ON t.id = o.tenant_id
  JOIN _rs_tenant k ON k.name = t.name AND k.room_label = t.room_label AND k.room_address = t.room_address
 WHERE o.user_id = @uid;
DELETE tp FROM tenant_payers tp
  JOIN tenants t ON t.id = tp.tenant_id
  JOIN _rs_tenant k ON k.name = t.name AND k.room_label = t.room_label AND k.room_address = t.room_address
 WHERE tp.user_id = @uid;
DELETE t FROM tenants t
  JOIN _rs_tenant k ON k.name = t.name AND k.room_label = t.room_label AND k.room_address = t.room_address
 WHERE t.user_id = @uid;

DELETE r FROM rooms r
  JOIN properties p ON p.id = r.property_id
  JOIN _rs_property k ON k.name = p.name
 WHERE r.user_id = @uid AND p.user_id = @uid;
DELETE p FROM properties p JOIN _rs_property k ON k.name = p.name WHERE p.user_id = @uid;

-- 3) insert the fixtures
INSERT INTO properties (user_id, name, city_region, address, timezone, status)
SELECT @uid, k.name, k.city_region, k.address, k.timezone, k.status FROM _rs_property k;

DROP TEMPORARY TABLE IF EXISTS _id_property;
CREATE TEMPORARY TABLE _id_property (k varchar(64) NOT NULL PRIMARY KEY, id bigint unsigned NOT NULL) ENGINE=InnoDB;
INSERT INTO _id_property (k, id)
SELECT k.k, p.id FROM properties p JOIN _rs_property k ON k.name = p.name WHERE p.user_id = @uid;

INSERT INTO rooms (user_id, property_id, room_label, capacity, monthly_rent_cents, due_day, status, active_from)
SELECT @uid, ip.id, k.room_label, k.capacity, k.monthly_rent_cents, k.due_day, k.status, k.active_from
  FROM _rs_room k JOIN _id_property ip ON ip.k = k.property_key;

DROP TEMPORARY TABLE IF EXISTS _id_room;
CREATE TEMPORARY TABLE _id_room (k varchar(64) NOT NULL PRIMARY KEY, id bigint unsigned NOT NULL) ENGINE=InnoDB;
INSERT INTO _id_room (k, id)
SELECT k.k, r.id FROM rooms r JOIN _id_property ip ON ip.id = r.property_id
  JOIN _rs_room k ON k.room_label = r.room_label AND k.property_key = ip.k
 WHERE r.user_id = @uid;

INSERT INTO tenants (user_id, name, display_alias, monthly_rent_cents, currency, interval_unit,
                     interval_count, billing_start_date, due_day, rent_start_date, rent_end_date,
                     status, room_label, room_address, property_hint)
SELECT @uid, k.name, k.display_alias, k.monthly_rent_cents, k.currency, 'month', 1,
       k.billing_start_date, k.due_day, k.rent_start_date, k.rent_end_date,
       k.status, k.room_label, k.room_address, k.property_hint
  FROM _rs_tenant k;

DROP TEMPORARY TABLE IF EXISTS _id_tenant;
CREATE TEMPORARY TABLE _id_tenant (k varchar(64) NOT NULL PRIMARY KEY, id bigint unsigned NOT NULL) ENGINE=InnoDB;
INSERT INTO _id_tenant (k, id)
SELECT k.k, t.id FROM tenants t
  JOIN _rs_tenant k ON k.name = t.name AND k.room_label = t.room_label AND k.room_address = t.room_address
 WHERE t.user_id = @uid;

INSERT INTO tenancy_agreements (user_id, room_id, contract_date, move_in_date, start_date, end_date,
                                monthly_rent_cents, currency, due_day, status)
SELECT @uid, ir.id, k.contract_date, k.move_in_date, k.start_date, k.end_date,
       k.monthly_rent_cents, k.currency, k.due_day, k.status
  FROM _rs_agreement k JOIN _id_room ir ON ir.k = k.room_key;

DROP TEMPORARY TABLE IF EXISTS _id_agreement;
CREATE TEMPORARY TABLE _id_agreement (k varchar(128) NOT NULL PRIMARY KEY, id bigint unsigned NOT NULL) ENGINE=InnoDB;
INSERT INTO _id_agreement (k, id)
SELECT k.k, ta.id FROM tenancy_agreements ta
  JOIN _id_room ir ON ir.id = ta.room_id
  JOIN _rs_agreement k ON k.room_key = ir.k AND k.start_date = ta.start_date
 WHERE ta.user_id = @uid;

INSERT INTO agreement_parties (user_id, agreement_id, tenant_id, responsibility_cents, joined_at, left_at, status)
SELECT @uid, ia.id, it.id, k.responsibility_cents, k.joined_at, k.left_at, k.status
  FROM _rs_party k JOIN _id_agreement ia ON ia.k = k.agreement_key
  JOIN _id_tenant it ON it.k = k.tenant_key;

-- The bank feed arrives unmatched; seed-match.sql performs the matching pass.
INSERT INTO payment_transactions (user_id, source, stable_transaction_key, direction, amount_cents,
                                  currency, transaction_time, description, reference, payer_name,
                                  payer_name_kind, parsed_period_month, parsed_period_source, match_status)
SELECT @uid, 'rosewood_seed', k.stable_transaction_key, 'income', k.amount_cents,
       'EUR', k.transaction_time, k.description, k.reference, k.payer_name,
       'confirmed', k.period_month, 'rosewood_seed', 'unmatched'
  FROM _rs_tx k;

INSERT INTO tenant_payers (user_id, tenant_id, payer_name_original, payer_name_normalized, source)
SELECT @uid, it.id, k.payer_name, k.payer_name_normalized, 'manual'
  FROM _rs_payer k JOIN _id_tenant it ON it.k = k.tenant_key;

COMMIT;

DROP TEMPORARY TABLE IF EXISTS _rs_property, _rs_room, _rs_tenant, _rs_agreement, _rs_party, _rs_tx, _rs_payer;
DROP TEMPORARY TABLE IF EXISTS _id_property, _id_room, _id_tenant, _id_agreement;

